Repository omu/nokul, pull requests merged in 2018-09, with the labels that each got.

#241 Upgrade bundler dependencies
  Gemfile
  Gemfile.lock
Labels: dependencies

#240 Yapılandırmaları düzenle
  Vagrantfile
  config/database.yml
  config/initializers/rollbar.rb
  docs/development/installation.md
  test/config/database_config_test.rb
Labels: improvement

#243 Artık kodu düzelt
  test/config/database_config_test.rb
Labels: bug

#244 Minor tweaks
  Vagrantfile
  config/locales/layouts/application/tr.yml
  docs/development/installation.md
  docs/development/rake-task.md
  docs/git/branch.md
  docs/git/commit.md
  docs/git/issue.md
  docs/git/pull-request.md
  docs/how-to/navigate-units.md
  docs/ops/dokku.md
  docs/style/validations.md
Labels: improvement

#249 Manage users from ui
  app/views/users/_addresses.html.erb
  config/routes.rb
  test/controllers/users_controller_test.rb
Labels: bug

#248 Disable rollbar in development and test
  config/initializers/rollbar.rb
Labels: improvement

#250 Reorganize KPS jobs under a module
  app/controllers/account/addresses_controller.rb
  app/controllers/account/identities_controller.rb
  app/jobs/kps/address_save_job.rb
  app/jobs/kps/identity_save_job.rb
  app/jobs/kps_address_save_job.rb
  app/jobs/kps_identity_save_job.rb
  app/models/accounts/student.rb
  app/models/user.rb
  test/jobs/kps_address_job_test.rb
  test/jobs/kps_identity_job_test.rb
  test/models/accounts/student_test.rb
  test/models/user_test.rb
Labels: improvement

#251 Improve employee workflows
  app/controllers/account/duties_controller.rb
  app/controllers/account/employees_controller.rb
  app/controllers/account/positions_controller.rb
  app/controllers/public_profile_controller.rb
  app/controllers/users_controller.rb
  app/models/accounts/duty.rb
  app/models/accounts/employee.rb
  app/views/account/duties/_form.html.erb
  app/views/account/duties/show.html.erb
  app/views/account/employees/show.html.erb
  app/views/account/positions/_form.html.erb
  app/views/users/_employees.html.erb
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/routes.rb
Labels: improvement

#255 Bitiş tarihi alanlarının ön tanımlı boş gelmesini sağla
  app/views/account/duties/_form.html.erb
  app/views/account/positions/_form.html.erb
Labels: bug

#263 Keep secrets in credentials.yml.enc
  .github/CODEOWNERS
  config/credentials.yml.enc
  config/secrets.yml
Labels: improvement

#264 Dokümanları product owner grubu için hazırla
  .github/CODEOWNERS
  docs/howto/arel-queries.md
  docs/howto/navigate-units.md
  docs/howto/navigate-users.md
  docs/product/.gitignore
Labels: product

#265 Diller için gerekli geliştirmeleri yap
  app/controllers/application_controller.rb
  app/controllers/languages_controller.rb
  app/models/language.rb
  app/views/languages/_form.html.erb
  app/views/languages/edit.html.erb
  app/views/languages/index.html.erb
  app/views/languages/new.html.erb
  app/views/languages/show.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/locales/models/languages/en.yml
  config/locales/models/languages/tr.yml
  config/routes.rb
  db/migrate/20180906103618_create_languages.rb
  db/schema.rb
  db/seeds.rb
  db/static_data/languages.yml
  lib/tasks/post_deploy/generate_permalinks.rake
  lib/tasks/post_deploy/import_languages.rake
  test/controllers/languages_controller_test.rb
  test/fixtures/languages.yml
  test/models/language_test.rb
Labels: feature

#270 Duty, Employee ve Position validasyonlarını düzenle
  .rubocop.yml
  app/models/accounts/employee.rb
  app/models/accounts/position.rb
  app/validators/duty_validator.rb
  app/validators/employee_validator.rb
  app/validators/position_validator.rb
  app/views/account/duties/_form.html.erb
  app/views/account/positions/_form.html.erb
  config/locales/validators/en.yml
  config/locales/validators/tr.yml
  test/fixtures/positions.yml
  test/models/accounts/duty_test.rb
  test/models/accounts/employee_test.rb
  test/models/accounts/position_test.rb
Labels: improvement

#275 Configure administrative units
  app/controllers/units_controller.rb
  app/models/unit.rb
  app/views/units/index.html.erb
  app/views/units/show.html.erb
  config/locales/models/units/en.yml
  config/locales/models/units/tr.yml
  db/migrate/20180910105541_change_yoksis_id_and_detsis_id_constraint_to_unit.rb
  db/schema.rb
  db/static_data/administrative_units.yml
  lib/tasks/kaysis/import_administrative_units.rake
  test/models/unit_test.rb
Labels: feature-step

#277 Kullanıcı profillerine MERNİS butonları ekle
  app/controllers/concerns/last_update_from_mernis.rb
  app/controllers/users_controller.rb
  app/views/users/_addresses.html.erb
  app/views/users/_identities.html.erb
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/routes.rb
Labels: feature-step

#283 Set agenda for committees
  app/controllers/committee/agenda_types_controller.rb
  app/controllers/committee/agendas_controller.rb
  app/controllers/committee/dashboard_controller.rb
  app/models/committees/agenda.rb
  app/models/committees/agenda_type.rb
  app/models/unit.rb
  app/views/committee/agenda_types/_form.html.erb
  app/views/committee/agenda_types/edit.html.erb
  app/views/committee/agenda_types/index.html.erb
  app/views/committee/agenda_types/new.html.erb
  app/views/committee/agendas/_form.html.erb
  app/views/committee/agendas/edit.html.erb
  app/views/committee/agendas/index.html.erb
  app/views/committee/agendas/new.html.erb
  app/views/committee/dashboard/index.html.erb
  app/views/committee/dashboard/show.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/locales/models/committees/en.yml
  config/locales/models/committees/tr.yml
  config/routes.rb
  db/migrate/20180912131204_create_agenda_types.rb
  db/migrate/20180913075455_create_agendas.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/post_deploy/create_unit_type_for_committee.rake
  test/controllers/committee/agenda_types_controller_test.rb
  test/controllers/committee/agendas_controller_test.rb
  test/fixtures/agenda_types.yml
  test/fixtures/agendas.yml
  test/fixtures/units.yml
  test/models/committees/agenda_test.rb
  test/models/committees/agenda_type_test.rb
Labels: feature-step

#296 Duty, Position ve Employee controller testlerini ekle
  test/controllers/accounts/duties_controller_test.rb
  test/controllers/accounts/employees_controller_test.rb
  test/controllers/accounts/positions_controller_test.rb
  test/fixtures/positions.yml
Labels: improvement

#298 Pagy için DRY geliştirmelerini yap
  app/controllers/application_controller.rb
  app/controllers/calendar/academic_calendars_controller.rb
  app/controllers/calendar/academic_terms_controller.rb
  app/controllers/calendar/calendar_titles_controller.rb
  app/controllers/calendar/calendar_types_controller.rb
  app/controllers/committee/agenda_types_controller.rb
  app/controllers/committee/agendas_controller.rb
  app/controllers/committee/dashboard_controller.rb
  app/controllers/concerns/pagy_backend_with_helpers.rb
  app/controllers/concerns/reference_resource.rb
  app/controllers/curriculum/courses_controller.rb
  app/controllers/languages_controller.rb
  app/controllers/locations/cities_controller.rb
  app/controllers/locations/countries_controller.rb
  app/controllers/studies/articles_controller.rb
  app/controllers/units_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/helpers/units_helper.rb
Labels: improvement

#304 Develop dalı otomatik deploy edilsin
  .circleci/config.yml
Labels: system

#305 Develop dalı şimdilik otomatik deploy edilmesin
  .circleci/config.yml
Labels: system

#303 Ders tanımla ve listeleme işlemlerini geliştir
  app/controllers/application_controller.rb
  app/controllers/curriculum/courses_controller.rb
  app/models/concerns/dynamic_search.rb
  app/models/curriculums/course.rb
  app/models/language.rb
  app/views/curriculum/courses/_form.html.erb
  app/views/curriculum/courses/_search.html.erb
  app/views/curriculum/courses/_select2.html.erb
  app/views/curriculum/courses/index.html.erb
  app/views/curriculum/courses/show.html.erb
  app/views/units/_search.html.erb
  app/views/users/_search.html.erb
  config/locales/defaults/en.yml
  config/locales/defaults/tr.yml
  config/locales/models/curriculums/en.yml
  config/locales/models/curriculums/tr.yml
  config/locales/models/units/en.yml
  config/locales/models/units/tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  db/migrate/20180621072455_create_courses.rb
  db/migrate/20180917205042_remove_language_and_abrogated_date_from_courses.rb
  db/migrate/20180917205119_rename_education_type_to_program_type.rb
  db/migrate/20180917205157_add_language_id_to_courses.rb
  db/schema.rb
  test/controllers/curriculum/courses_controller_test.rb
  test/fixtures/courses.yml
  test/helpers/enum_i18n_helper_test.rb
  test/models/curriculums/course_test.rb
  test/models/language_test.rb
Labels: feature-step, improvement

#310 Müfredat dizininin adını ders yönetimi olarak değiştir
  app/controllers/course_management/courses_controller.rb
  app/models/course_management/course.rb
  app/views/course_management/courses/_form.html.erb
  app/views/course_management/courses/_search.html.erb
  app/views/course_management/courses/_select2.html.erb
  app/views/course_management/courses/edit.html.erb
  app/views/course_management/courses/index.html.erb
  app/views/course_management/courses/new.html.erb
  app/views/course_management/courses/show.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/locales/models/course_management/en.yml
  config/locales/models/course_management/tr.yml
  config/routes.rb
  test/controllers/course_management/courses_controller_test.rb
  test/models/course_management/course_test.rb
Labels: improvement

#307 Invoke administrative unit task from seed
  db/seeds.rb
Labels: improvement

#311 Document için model ve controller ekle
  app/controllers/documents_controller.rb
  app/models/document.rb
  app/views/documents/_form.html.erb
  app/views/documents/edit.html.erb
  app/views/documents/index.html.erb
  app/views/documents/new.html.erb
  app/views/documents/show.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/locales/models/documents/en.yml
  config/locales/models/documents/tr.yml
  config/routes.rb
  db/migrate/20180918151443_create_documents.rb
  db/schema.rb
  test/controllers/documents_controller_test.rb
  test/fixtures/documents.yml
  test/models/document_test.rb
Labels: feature-step

#312 Dinamik selectbox oluşturmak için js helper ekle
  app/assets/javascripts/application.js
  app/assets/javascripts/helpers/dynamic_select.js
Labels: improvement

#327 Birim modeli için iyileştirmeler yap
  app/controllers/concerns/reference_resource.rb
  app/controllers/references/unit_types_controller.rb
  app/controllers/units_controller.rb
  app/models/references/unit_status.rb
  app/models/references/unit_type.rb
  app/models/unit.rb
  app/views/references/unit_types/_form.html.erb
  app/views/references/unit_types/index.html.erb
  config/locales/models/references/en.yml
  config/locales/models/references/tr.yml
  db/migrate/20180919115101_add_group_to_unit_type.rb
  db/schema.rb
  test/fixtures/unit_types.yml
  test/fixtures/units.yml
  test/models/references/unit_status_test.rb
  test/models/references/unit_type_test.rb
  test/models/unit_test.rb
Labels: improvement

#338 Belgelerin yalnızca programlarla ilişkilendirilmesini sağla
  app/controllers/registration_documents_controller.rb
  app/views/units/show.html.erb
  test/fixtures/registration_documents.yml
Labels: feature-step
