Repository omu/nokul, pull requests merged in 2018-08, with the labels that each got.

#148 toggler visible only on md
  app/views/layouts/application.html.erb
Labels: UX, improvement

#152 Add footer to guest template
  app/assets/stylesheets/custom/guest_background.css.erb
  app/assets/stylesheets/custom/guest_footer.css
  app/assets/stylesheets/guest.scss
  app/views/layouts/guest.html.erb
  app/views/layouts/shared/_footer.html.erb
Labels: UX, bug

#160 Tidy up
  app/controllers/account/addresses_controller.rb
  app/controllers/account/identities_controller.rb
  app/controllers/concerns/last_update_from_mernis.rb
  app/helpers/membership_notifications_helper.rb
  app/models/accounts/address.rb
  app/models/accounts/identity.rb
  app/validators/address_and_identity_validator.rb
  app/validators/address_validator.rb
  app/validators/identity_validator.rb
  app/views/account/addresses/_form.html.erb
  app/views/account/addresses/index.html.erb
  app/views/account/identities/index.html.erb
  app/views/home/components/_membership_notifications.html.erb
  app/views/home/components/_user_and_account_statistics.html.erb
  config/locales/layouts/application/en.yml
  config/locales/layouts/application/tr.yml
  config/locales/models/addresses/en.yml
  config/locales/models/addresses/tr.yml
  config/locales/models/home/en.yml
  config/locales/models/home/tr.yml
  config/locales/models/identities/en.yml
  config/locales/models/identities/tr.yml
  db/migrate/20180802132337_rename_name_field_of_identity_and_address_to_type.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/yoksis/import_departments.rake
  test/controllers/accounts/addresses_controller_test.rb
  test/controllers/accounts/identities_controller_test.rb
  test/fixtures/addresses.yml
  test/fixtures/identities.yml
  test/fixtures/students.yml
  test/fixtures/yoksis_responses.yml
  test/models/accounts/address_test.rb
  test/models/accounts/identity_test.rb
  test/models/accounts/student_test.rb
  test/test_helper.rb
Labels: improvement

#185 Upgrade to rails 5.2.1
  Gemfile.lock
  bin/yarn
  test/config/application_config_test.rb
Labels: improvement

#189 Added latest tag as app version to footer
  app/views/layouts/shared/_footer.html.erb
  config/initializers/git_version.rb
Labels: improvement

#206 Added new workflows to Circleci
  .circleci/config.yml
  .circleci/parallel_workflow.yml
  .circleci/sequential_basic_workflow.yml
  Gemfile
Labels: system

#219 Gemfile'a ruby versiyonu ekle
  .circleci/parallel_workflow.yml
  .ruby-version
  Gemfile
Labels: system

#223 .ruby-version dosyasını depoda tut
  .circleci/parallel_workflow.yml
  .ruby-version
  Gemfile
Labels: system

#222 Fix cache keys of CircleCI
  .circleci/config.yml
  .circleci/parallel_workflow.yml
  .circleci/sequential_basic_workflow.yml
  app/views/users/_addresses.html.erb
  config/routes.rb
Labels: system

#220 Add guides and developer docs
  Gemfile
  Gemfile.lock
  README.md
  docs/CONTRIBUTING.md
  docs/development/app-upgrade.md
  docs/development/installation.md
  docs/development/mernis-test-data.md
  docs/development/rake-task.md
  docs/development/test-coverage.md
  docs/development/third-parties.md
  docs/git/branch.md
  docs/git/commit.md
  docs/git/issue.md
  docs/git/pull-request.md
  docs/git/review.md
  docs/how-to/arel-queries.md
  docs/how-to/navigate-units.md
  docs/how-to/navigate-users.md
  docs/ops/dokku.md
  docs/style/validations.md
  lib/tasks/pr.rake
Labels: improvement

#228 Reorganize gemfile
  .circleci/config.yml
  .circleci/parallel_workflow.yml
  .circleci/sequential_basic_workflow.yml
  Gemfile
  Gemfile.lock
Labels: system

#229 Add start date and end date to position
  app/controllers/account/positions_controller.rb
  app/models/accounts/position.rb
  app/views/account/duties/show.html.erb
  app/views/account/positions/_form.html.erb
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  db/migrate/20180817060355_add_start_date_and_end_date_to_position.rb
  db/schema.rb
  test/fixtures/positions.yml
  test/models/accounts/position_test.rb
Labels: improvement

#233 Upgrade bundler dependencies
  Gemfile.lock
Labels: dependencies
