Repository omu/nokul, pull requests merged in 2018-07, with the labels that each got.

#102 Articles and certifications
  app/jobs/yoksis/articles_create_job.rb
  app/jobs/yoksis/certifications_create_job.rb
  app/jobs/yoksis_publications_create_job.rb
  app/models/academic_studies/article.rb
  app/models/academic_studies/certification.rb
  app/models/user.rb
  app/services/yoksis/v1/ozgecmis.rb
  config/application.rb
  db/migrate/20180710213813_create_articles.rb
  db/schema.rb
Labels: feature-step

#103 Academic projects
  Gemfile.lock
  app/jobs/yoksis/articles_create_job.rb
  app/jobs/yoksis/certifications_create_job.rb
  app/jobs/yoksis/projects_create_job.rb
  app/models/academic_studies/article.rb
  app/models/academic_studies/project.rb
  app/models/user.rb
  app/services/yoksis/v1/ozgecmis.rb
  db/migrate/20180712130547_create_projects.rb
  db/schema.rb
Labels: feature-step

#113 Academic studies
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/controllers/studies/articles_controller.rb
  app/controllers/studies/certifications_controller.rb
  app/controllers/studies/dashboard_controller.rb
  app/controllers/studies/projects_controller.rb
  app/helpers/apa_helper.rb
  app/jobs/yoksis/articles_create_job.rb
  app/models/academic_studies/article.rb
  app/models/academic_studies/certification.rb
  app/models/academic_studies/project.rb
  app/models/unit.rb
  app/models/user.rb
  app/views/layouts/shared/_sidebar.html.erb
  app/views/studies/articles/index.html.erb
  app/views/studies/certifications/index.html.erb
  app/views/studies/dashboard/index.html.erb
  app/views/studies/projects/index.html.erb
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/locales/models/studies/en.yml
  config/locales/models/studies/tr.yml
  config/routes.rb
  db/migrate/20180713221157_add_articles_count_to_users.rb
  db/migrate/20180713222542_add_projects_count_to_users.rb
  db/migrate/20180713224006_add_timestamps_to_publishings.rb
  db/schema.rb
  lib/tasks/counter_cache/update_counter_cache.rake
  lib/tasks/yoksis/import_yoksis_country_codes.rake
Labels: feature-step

#117 add last_name and unit of the author
  app/views/studies/articles/index.html.erb
Labels: improvement

#120 Fixes #119
  app/views/studies/articles/index.html.erb
Labels: bug

#122 Update dependencies
  Gemfile.lock
  app/models/user.rb
Labels: improvement

#124 Guest template'ine dil değişikliği için bayrak ikonlarını ekle
  app/views/layouts/guest.html.erb
Labels: improvement
