Repository omu/nokul, pull requests merged in 2019-07, with the labels that each got.

#955 Upgrade bundler dependencies
  Gemfile.lock
Labels: chore, dependencies

#956 Upgrade yarn dependencies
  yarn.lock
Labels: chore, dependencies

#964 Telefon alanları için intl-tel-input kitaplığını kullan
  app/assets/javascripts/application.js
  app/assets/javascripts/guest.js
  app/assets/javascripts/shared/intl_tel_input_utils.js
  app/assets/javascripts/shared/intl_tel_input_validation.js
  app/assets/stylesheets/application.scss
  app/controllers/account/registrations_controller.rb
  app/services/activation/activation_service.rb
  app/views/account/activations/_js.html.erb
  app/views/account/activations/new.html.erb
  app/views/account/registrations/edit.html.erb
  config/initializers/assets.rb
  config/locales/gems/intl_tel_input/en.yml
  config/locales/gems/intl_tel_input/tr.yml
  package.json
  test/controllers/accounts/activation_controller_test.rb
  test/services/activation/activation_service_test.rb
  yarn.lock
Labels: improvement

#966 JavaScript dosyaları için lint görevi ekle
  lib/tasks/static_analysis/all.rake
  lib/tasks/static_analysis/eslint.rake
Labels: chore, improvement

#967 Upgrade bundler dependencies
  Gemfile.lock
  app/models/agenda.rb
  app/models/agenda_type.rb
  app/models/available_course.rb
  app/models/calendar.rb
  app/models/calendar_event_type.rb
  app/models/city.rb
  app/models/concerns/reference_search.rb
  app/models/country.rb
  app/models/course.rb
  app/models/course_group.rb
  app/models/course_group_type.rb
  app/models/course_type.rb
  app/models/curriculum.rb
  app/models/district.rb
  app/models/ldap_entity.rb
  app/models/patron/permission.rb
  app/models/patron/query_store.rb
  app/models/patron/role.rb
  app/models/prospective_employee.rb
  app/models/prospective_student.rb
  app/models/registration_document.rb
  app/models/unit.rb
  app/models/user.rb
Labels: dependencies
