Repository omu/nokul, pull requests merged in 2019-04, with the labels that each got.

#895 Account activation
  app/assets/javascripts/guest.js
  app/assets/stylesheets/guest.scss
  app/controllers/account/activations_controller.rb
  app/controllers/first_registration/prospective_students_controller.rb
  app/models/prospective_student.rb
  app/models/user.rb
  app/services/activation/student_activation_service.rb
  app/validators/activation_service_validator.rb
  app/views/account/activations/_js.html.erb
  app/views/account/activations/new.html.erb
  app/views/account/sessions/new.html.erb
  app/views/layouts/guest.html.erb
  app/views/users/_account.html.erb
  config/locales/controllers/account/activations.en.yml
  config/locales/controllers/account/activations.tr.yml
  config/locales/controllers/account/devise.en.yml
  config/locales/controllers/account/devise.tr.yml
  config/locales/controllers/account/sessions.en.yml
  config/locales/controllers/account/sessions.tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/locales/validators/en.yml
  config/locales/validators/tr.yml
  config/routes/account.rb
  db/migrate/20190325051222_add_activated_to_user.rb
  db/structure.sql
  test/controllers/accounts/activation_controller_test.rb
  test/fixtures/prospective_students.yml
  test/fixtures/users.yml
  test/models/user_test.rb
  test/services/activation/student_activation_service_test.rb
  test/system/login_page_flow_test.rb
Labels: feature, feature step

#899 Git secrets desteği ekle
  .gitallowed
  app/models/address.rb
  app/models/user.rb
  app/services/activation/student_activation_service.rb
  doc/git/commit.md
  lib/tasks/security.rake
  plugins/support/test/codification/memory_test.rb
  plugins/support/test/core_ext/class_test.rb
  plugins/tenant/common/.rubocop.yml
  plugins/tenant/common/lib/nokul/tenant.rb
  plugins/tenant/common/lib/nokul/tenant/engine.rb
Labels: security

#901 Seed İşleminde Oluşan Hatayı Düzelt
  .gitattributes
  db/encrypted_data/sample_data.sql.enc.gz
  db/encrypted_data/sample_data.tar.gz
  db/encrypted_data/static_data.sql.enc.gz
  db/encrypted_data/static_data.tar.gz
  db/seeds.rb
  db/structure.sql
  lib/tasks/dump.rake
  plugins/support/lib/nokul/support/sensitive.rb
Labels: bug, improvement
