Repository omu/nokul, pull requests merged in 2019-02, with the labels that each got.

#751 Akademik takvim ile kurul kararlarını ilişkilendir
  .hound.yml
  app/controllers/calendar_management/calendars_controller.rb
  app/models/calendar.rb
  app/models/calendar_committee_decision.rb
  app/models/committee_decision.rb
  app/models/unit.rb
  app/models/unit_type.rb
  app/views/calendar_management/calendars/_flatpickr.html.erb
  app/views/calendar_management/calendars/_form.html.erb
  app/views/calendar_management/calendars/index.html.erb
  app/views/calendar_management/calendars/show.html.erb
  app/views/calendar_management/calendars/show.pdf.erb
  config/locales/controllers/calendar_management/calendars.en.yml
  config/locales/controllers/calendar_management/calendars.tr.yml
  db/beta_seed/calendar.rb
  db/migrate/20190130105509_remove_senate_decision_columns_from_calendar.rb
  db/migrate/20190130114547_create_calendar_committee_decisions.rb
  db/structure.sql
  test/controllers/calendar_management/calendars_controller_test.rb
  test/fixtures/calendar_committee_decisions.yml
  test/fixtures/calendars.yml
  test/fixtures/unit_types.yml
  test/fixtures/units.yml
  test/models/calendar_committee_decision_test.rb
  test/models/calendar_test.rb
  test/models/unit_test.rb
  test/models/unit_type_test.rb
Labels: feature step, improvement

#773 Açılan ders gruplarının öğretim elemansız oluşturulmasını engelle
  app/controllers/course_management/available_course_groups_controller.rb
  app/models/available_course_group.rb
  app/validators/available_course_lecturer_validator.rb
  app/validators/course_evaluation_type_validator.rb
  app/views/course_management/available_course_groups/_form.html.erb
  app/views/course_management/available_course_groups/_js.html.erb
  app/views/course_management/available_course_groups/_lecturer_fields.html.erb
  config/locales/controllers/course_management/available_course_groups.en.yml
  config/locales/controllers/course_management/available_course_groups.tr.yml
  test/controllers/course_management/available_course_groups_controller_test.rb
  test/controllers/course_management/curriculums_controller_test.rb
  test/fixtures/curriculums.yml
Labels: bug, improvement

#785 Vagrantfile'a Openldap sunucusu ekle
  Vagrantfile
  lib/scripts/ldap.sh
  lib/templates/ldap/README.md
  lib/templates/ldap/config/01-enable-bcrypt.ldif
  lib/templates/ldap/config/02-disallow-anon.ldif
  lib/templates/ldap/config/03-admin-normal-password.ldif
  lib/templates/ldap/config/04-admin-config-password.ldif
  lib/templates/ldap/config/05-enable-dynlist.ldif
  lib/templates/ldap/config/06-dynlist-dbconfig.ldif
  lib/templates/ldap/config/import.ldif
  lib/templates/ldap/config/import_treduperson.ldif
  lib/templates/ldap/config/schema/core.schema
  lib/templates/ldap/config/schema/cosine.schema
  lib/templates/ldap/config/schema/eduperson.ldif
  lib/templates/ldap/config/schema/eduperson.schema
  lib/templates/ldap/config/schema/eduperson2016.ldif
  lib/templates/ldap/config/schema/inetorgperson.schema
  lib/templates/ldap/config/schema/schac-schema-1.5.ldif
  lib/templates/ldap/config/schema/trEduPerson.schema
Labels: in progress, system

#743 KPS doğrulama metotlarını iyileştir
  app/services/xokul/kps.rb
  app/services/xokul/kps/verification.rb
Labels: feature

#786 Travis integration
  .circleci/config.yml
  .gitignore
  .travis.yml
  Dockerfile
  app.json
  config/database.yml
  config/deploy_key.enc
  docker-compose.yml
  lib/scripts/paas.sh
  lib/tasks/security.rake
  test/application_system_test_case.rb
Labels: in progress, system
