Repository omu/nokul, pull requests merged in 2019-12, with the labels that each got.

#1269 Fix rubocop offenses
  Gemfile
  app/models/prospective_employee.rb
  app/models/user.rb
  test/models/user_test.rb
Labels: bug

#1270 Tidy up
  .codacy.yml
  doc/plugins/tenant/common/development/tenant.md
  lib/scripts/ldap.sh
Labels: improvement

#1236 Öğrencinin ders seçimini yapmasını sağla
  app/controllers/course_management/enrolled_courses_controller.rb
  app/controllers/studentship/course_enrollments_controller.rb
  app/decorators/curriculum_decorator.rb
  app/decorators/curriculum_semester_decorator.rb
  app/decorators/student_decorator.rb
  app/models/academic_term.rb
  app/models/available_course.rb
  app/models/calendar.rb
  app/models/course_enrollment.rb
  app/models/curriculum_course_group.rb
  app/models/curriculum_semester.rb
  app/models/prospective_student.rb
  app/models/student.rb
  app/services/student_course_enrollment_service.rb
  app/views/course_management/enrolled_courses/_available_courses.html.erb
  app/views/course_management/enrolled_courses/_semesters.html.erb
  app/views/course_management/enrolled_courses/index.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  app/views/studentship/course_enrollments/_available_courses.html.erb
  app/views/studentship/course_enrollments/_course_enrollments.html.erb
  app/views/studentship/course_enrollments/_semesters.html.erb
  app/views/studentship/course_enrollments/_student_info.html.erb
  app/views/studentship/course_enrollments/index.html.erb
  app/views/studentship/course_enrollments/list.html.erb
  app/views/studentship/course_enrollments/new.html.erb
  config/environments/production.rb
  config/locales/controllers/course_management/enrolled_courses.en.yml
  config/locales/controllers/course_management/enrolled_courses.tr.yml
  config/locales/controllers/studentship/course_enrollments.en.yml
  config/locales/controllers/studentship/course_enrollments.tr.yml
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/routes.rb
  config/routes/course_management.rb
  config/routes/studentship.rb
  db/migrate/20191018084942_create_course_enrollments.rb
  db/migrate/20191021073002_add_semester_and_year_to_students.rb
  db/structure.sql
  test/controllers/course_management/enrolled_courses_controller_test.rb
  test/controllers/studentship/course_enrollments_controller_test.rb
  test/decorators/curriculum_semester_decorator_test.rb
  test/decorators/student_decorator_test.rb
  test/fixtures/available_course_groups.yml
  test/fixtures/available_courses.yml
  test/fixtures/calendar_events.yml
  test/fixtures/calendars.yml
  test/fixtures/course_enrollments.yml
  test/fixtures/curriculum_course_groups.yml
  test/fixtures/curriculum_courses.yml
  test/fixtures/curriculum_semesters.yml
  test/fixtures/students.yml
  test/fixtures/unit_calendars.yml
  test/models/available_course_test.rb
  test/models/calendar_test.rb
  test/models/course_enrollment_test.rb
  test/models/curriculum_course_group_test.rb
  test/models/curriculum_semester_test.rb
  test/models/student_test.rb
  test/services/student_course_enrollment_service_test.rb
Labels: feature

#1274 MEKSİS tanımını refaktör et
  app/assets/images/meksis/baum.png
  app/assets/images/meksis/omu.jpg
  app/views/meksis/buildings/index.html.erb
  app/views/meksis/buildings/index.pdf.erb
  app/views/meksis/classrooms/show.html.erb
  config/locales/controllers/meksis/buildings.en.yml
  config/locales/controllers/meksis/buildings.tr.yml
  plugins/tenant/acme/config/tenant.yml
  plugins/tenant/omu/config/tenant.yml
Labels: bug

#1279 Arttırılabilr AKTS miktarı ve GANO hesaplamalarında düzeltme yap
  app/models/student.rb
  app/services/student_course_enrollment_service.rb
  test/models/student_test.rb
  test/services/student_course_enrollment_service_test.rb
Labels: bug

#1276 Akademik personel Ar/Ge çalışmalarına bildirileri ekle
  app/controllers/account/profile_controller.rb
  app/controllers/account/yoksis_services_controller.rb
  app/jobs/yoksis/papers_save_job.rb
  app/models/paper.rb
  app/models/user.rb
  app/views/account/profile/index.html.erb
  app/views/account/profile/papers.js.erb
  app/views/account/profile/partials/_papers.html.erb
  config/locales/controllers/account/profile.en.yml
  config/locales/controllers/account/profile.tr.yml
  config/locales/controllers/account/yoksis_services.en.yml
  config/locales/controllers/account/yoksis_services.tr.yml
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  config/routes/account.rb
  db/migrate/20191127055945_create_papers.rb
  db/structure.sql
Labels: feature

#1283 Update .gitallowed list
  .gitallowed
Labels: improvement

#1284 OpenID Connect entegrasyonu ekle
  Gemfile
  Gemfile.lock
  Vagrantfile
  app/controllers/account/omniauth_callbacks_controller.rb
  app/controllers/account/sessions_controller.rb
  app/models/user.rb
  app/views/layouts/shared/_header.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/initializers/ssl.rb
  config/routes/account.rb
  doc/app/sso.md
  doc/development/sso.md
  lib/scripts/deploy.sh
  lib/scripts/ldap.sh
  lib/scripts/sso.sh
  lib/tasks/static_analysis/all.rake
  lib/tasks/static_analysis/audit.rake
  lib/templates/ldap/config/import.ldif
  lib/templates/sso/etc/nginx/dhparam.pem
  lib/templates/sso/etc/nginx/portal-nginx.conf
  lib/templates/sso/etc/nginx/snippets/ssl-params.conf
  lib/templates/sso/etc/oidc.key
  lib/templates/sso/etc/oidc_pub.key
  lib/templates/sso/portal/customLoginFooter.tpl
  lib/templates/sso/portal/customLoginHeader.tpl
  lib/templates/sso/portal/customfooter.tpl
  lib/templates/sso/portal/customhead.tpl
  lib/templates/sso/portal/customheader.tpl
  plugins/tenant/acme/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/test.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/test.yml.enc
Labels: feature

#1307 LemonLDAP dokümanı ekle
  doc/app/sso.md
Labels: doc

#1309 Aday öğrenci kayıtlarında validasyon düzenlemesi yap
  app/models/prospective_student.rb
  app/validators/prospective_student_validator.rb
  app/views/first_registration/prospective_students/_form.html.erb
  config/locales/validators/en.yml
  config/locales/validators/tr.yml
  test/validators/prospective_student_validator_test.rb
Labels: bug, qa

#1328 Delete .gitattributes
  .gitattributes
Labels: chore

#1329 S3 görevinde git yerine Rails metodu kullan
  lib/tasks/s3.rake
Labels: bug

#1354 Tidy up
  .erb-lint.yml
  .rubocop.yml
  .rubocop_common.yml
  Gemfile.lock
  package.json
  plugins/support/.rubocop.yml
  plugins/tenant/acme/.rubocop.yml
  plugins/tenant/common/.rubocop.yml
  plugins/tenant/omu/.rubocop.yml
  yarn.lock
Labels: improvement

#1353 Eksik model ve controller testlerini ekle
  config/locales/controllers/course_management/available_courses.en.yml
  config/locales/controllers/course_management/available_courses.tr.yml
  config/locales/controllers/meksis/buildings.en.yml
  config/locales/controllers/meksis/buildings.tr.yml
  config/routes/meksis.rb
  test/controllers/meksis/buildings_controller_test.rb
  test/controllers/meksis/classrooms_controller_test.rb
  test/controllers/meksis/dashboard_controller_test.rb
  test/controllers/meksis/place_types_controller_test.rb
  test/fixtures/articles.yml
  test/fixtures/buildings.yml
  test/fixtures/certifications.yml
  test/fixtures/classrooms.yml
  test/fixtures/papers.yml
  test/fixtures/place_types.yml
  test/models/article_test.rb
  test/models/building_test.rb
  test/models/certification_test.rb
  test/models/classroom_test.rb
  test/models/paper_test.rb
  test/models/place_type_test.rb
Labels: qa

#1372 Örnek seed verilerine cezmi kullanıcısını ekle
  db/beta_seed/user.rb
  db/seeds.rb
Labels: improvement
