Repository omu/nokul, pull requests merged in 2019-09, with the labels that each got.

#988 Ruby sürümünü yükselt
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  plugins/support/.ruby-version
  plugins/support/Gemfile
  plugins/support/Gemfile.lock
  plugins/tenant/common/.ruby-version
  plugins/tenant/common/Gemfile
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/.ruby-version
  plugins/tenant/omu/Gemfile
  plugins/tenant/omu/Gemfile.lock
  yarn.lock
Labels: dependencies, urgent

#991 Personal setting page
  app/assets/javascripts/shared/intl_tel_input_validation.js
  app/controllers/account/registrations_controller.rb
  app/controllers/account/settings/emails_controller.rb
  app/controllers/account/settings/passwords_controller.rb
  app/controllers/account/settings/phones_controller.rb
  app/controllers/account/settings_controller.rb
  app/views/account/registrations/edit.html.erb
  app/views/account/settings/emails/edit.html.erb
  app/views/account/settings/index.html.erb
  app/views/account/settings/passwords/edit.html.erb
  app/views/account/settings/phones/edit.html.erb
  app/views/account/settings/phones/verification.js.erb
  app/views/home/components/_membership_notifications.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/shared/_header.html.erb
  config/locales/controllers/account/registrations.en.yml
  config/locales/controllers/account/registrations.tr.yml
  config/locales/controllers/account/settings.en.yml
  config/locales/controllers/account/settings.tr.yml
  config/locales/controllers/account/settings/emails.en.yml
  config/locales/controllers/account/settings/emails.tr.yml
  config/locales/controllers/account/settings/passwords.en.yml
  config/locales/controllers/account/settings/passwords.tr.yml
  config/locales/controllers/account/settings/phones.en.yml
  config/locales/controllers/account/settings/phones.tr.yml
  config/locales/layouts/application/en.yml
  config/locales/layouts/application/tr.yml
  config/locales/layouts/shared/header.en.yml
  config/locales/layouts/shared/header.tr.yml
  config/routes/account.rb
  test/controllers/accounts/settings/emails_controller_test.rb
  test/controllers/accounts/settings/passwords_controller_test.rb
  test/system/account_settings_page_flow_test.rb
Labels: feature

#993 Dependabot yapılandırması ekle
  .dependabot/config.yml
Labels: chore, feature

#1008 CONTRIBUTING.md was updated for "branch link".
  .github/CONTRIBUTING.md
Labels: bug

#1010 Katkı sunma rehberini güncelle
  .github/CONTRIBUTING.md
Labels: chore
