Repository omu/nokul, pull requests merged in 2019-06, with the labels that each got.

#926 Tidy up
  .rubocop.yml
  app/models/unit.rb
  app/views/units/show.html.erb
  config/initializers/devise.rb
  db/encrypted_data/sample_data.sql.enc.gz
  db/encrypted_data/static_data.sql.enc.gz
  db/seeds.rb
  lib/tasks/import/units.rake
  test/system/reset_password_flow_test.rb
Labels: improvement

#922 Telefon doğrulama kodunu aktivasyon sayfasına ekle
  app/assets/javascripts/guest.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/coreui.scss
  app/assets/stylesheets/guest.scss
  app/controllers/account/activations_controller.rb
  app/controllers/account/addresses_controller.rb
  app/controllers/account/profile_settings_controller.rb
  app/models/address.rb
  app/models/prospective_employee.rb
  app/models/prospective_student.rb
  app/models/user.rb
  app/services/activation/activation_service.rb
  app/services/twilio/verify.rb
  app/views/account/activations/_modal.html.erb
  app/views/account/activations/create.js.erb
  app/views/account/activations/new.html.erb
  app/views/account/addresses/_form.html.erb
  app/views/account/addresses/index.html.erb
  app/views/account/profile_settings/edit.html.erb
  app/views/users/_addresses.html.erb
  config/credentials.yml.enc
  config/locales/controllers/account/activations.en.yml
  config/locales/controllers/account/activations.tr.yml
  config/locales/controllers/account/profile.en.yml
  config/locales/controllers/account/profile.tr.yml
  config/locales/gems/twilio/en.yml
  config/locales/gems/twilio/tr.yml
  config/locales/models/addresses/en.yml
  config/locales/models/addresses/tr.yml
  config/locales/validators/en.yml
  config/locales/validators/tr.yml
  config/routes/account.rb
  db/migrate/20190529121036_add_mobile_phone_to_user.rb
  db/structure.sql
  plugins/tenant/omu/test/dummy/config/credentials.yml.enc
  test/controllers/accounts/activation_controller_test.rb
  test/controllers/accounts/addresses_controller_test.rb
  test/fixtures/addresses.yml
  test/models/address_test.rb
  test/models/prospective_employee_test.rb
  test/models/prospective_student_test.rb
  test/models/user_test.rb
  test/services/activation/activation_service_test.rb
  test/system/profile_setting_flow_test.rb
Labels: feature

#927 Rake görevlerini refaktör et
  .gitignore
  .travis.yml
  README.md
  db/encrypted_data/academics.csv.enc
  db/encrypted_data/academics.yml.enc
  doc/README.md
  lib/tasks/database.rake
  lib/tasks/db/all.rake
  lib/tasks/db/dump.rake
  lib/tasks/db/index.rake
  lib/tasks/developer.rake
  lib/tasks/dump.rake
  lib/tasks/fetch/academic_staff.rake
  lib/tasks/fetch/references.rake
  lib/tasks/import/cities.rake
  lib/tasks/import/countries.rake
  lib/tasks/import/detsis_unit_types.rake
  lib/tasks/import/districts.rake
  lib/tasks/import/high_school_types.rake
  lib/tasks/import/languages.rake
  lib/tasks/import/titles.rake
  lib/tasks/import/unit_groups.rake
  lib/tasks/import/update_names_depth_cache.rake
  lib/tasks/import/yoksis_countries.rake
  lib/tasks/import/yoksis_country_codes.rake
  lib/tasks/nokul/archive_prospective_students.rake
  lib/tasks/nokul/update_counter_cache.rake
  lib/tasks/prerequisities.rake
  lib/tasks/pull_request.rake
  lib/tasks/quality.rake
  lib/tasks/security.rake
  lib/tasks/static_analysis/all.rake
  lib/tasks/static_analysis/audit.rake
  lib/tasks/static_analysis/brakeman.rake
  lib/tasks/static_analysis/erb_linter.rake
  lib/tasks/static_analysis/executables.rake
  lib/tasks/static_analysis/html_linter.rake
  lib/tasks/static_analysis/liche.rake
  lib/tasks/static_analysis/markdownlint.rake
  lib/tasks/static_analysis/rubocop.rake
  lib/tasks/static_analysis/secrets.rake
  package.json
  yarn.lock
Labels: improvement

#931 Linter hatalarını düzelt
  Gemfile.lock
  db/seeds.rb
  doc/plugins/support/sensitive.md
  doc/plugins/support/structure.md
  doc/plugins/tenant/common/development/tenant.md
  lib/tasks/db/dump.rake
  lib/tasks/fetch/references.rake
  lib/tasks/import/districts.rake
  lib/tasks/import/update_names_depth_cache.rake
  lib/tasks/import/yoksis_countries.rake
  lib/tasks/prerequisities.rake
  lib/tasks/static_analysis/liche.rake
  lib/tasks/static_analysis/markdownlint.rake
  lib/tasks/static_analysis/rubocop.rake
Labels: chore, urgent

#934 Xokul istemcisine Meksis'i ekle
  app/services/xokul/meksis.rb
  doc/app/xokul.md
Labels: feature

#938 CI'daki ruby-vips ve webdrivers hatasını düzelt
  Gemfile
  Gemfile.lock
  test/application_system_test_case.rb
  test/system/vips_test.rb
Labels: bug

#939 Kullanıcı telefon numaralarının güncellenebilmesini sağla
  app/assets/javascripts/application.js
  app/controllers/account/activations_controller.rb
  app/controllers/account/registrations_controller.rb
  app/controllers/concerns/phone_verification.rb
  app/models/user.rb
  app/services/activation/activation_service.rb
  app/services/twilio/verify.rb
  app/views/account/activations/create.js.erb
  app/views/account/registrations/edit.html.erb
  app/views/account/registrations/phone_verification.js.erb
  app/views/layouts/shared/_phone_verification_modal.html.erb
  config/locales/controllers/account/activations.en.yml
  config/locales/controllers/account/activations.tr.yml
  config/locales/controllers/account/registrations.en.yml
  config/locales/controllers/account/registrations.tr.yml
  config/locales/errors/en.yml
  config/locales/errors/tr.yml
  config/locales/layouts/shared/phone_verification_modal.en.yml
  config/locales/layouts/shared/phone_verification_modal.tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/routes/account.rb
  test/controllers/accounts/activation_controller_test.rb
Labels: feature

#942 Telefon güncelleme işleminde ülke bilgisinin seçilmesini sağla
  app/controllers/account/registrations_controller.rb
  app/views/account/registrations/edit.html.erb
  app/views/account/registrations/phone_verification.js.erb
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
Labels: debt, improvement
