Repository omu/nokul, pull requests merged in 2019-03, with the labels that each got.

#846 Database yapılandırmasını düzelt
  config/application.rb
  config/database.yml
  docker-compose.yml
Labels: bug

#851 Upgrade Rails to 6.0.0.beta3
  Gemfile.lock
Labels: security

#854 Upgrade plugin dependencies
  plugins/support/Gemfile.lock
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/Gemfile.lock
Labels: dependencies, security

#855 Fix encrypted seed data
  db/encrypted_data/sample_data.tar.gz
  db/encrypted_data/static_data.tar.gz
  db/seeds.rb
Labels: bug

#844 Manuel aday öğrenci oluşturulmasını sağla
  .rubocop.yml
  app/controllers/first_registration/prospective_students_controller.rb
  app/decorators/prospective_student_decorator.rb
  app/jobs/osym/import_prospective_students_job.rb
  app/models/academic_term.rb
  app/models/prospective_student.rb
  app/views/account/addresses/index.html.erb
  app/views/account/identities/_form.html.erb
  app/views/account/identities/index.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/first_registration/prospective_students/_form.html.erb
  app/views/first_registration/prospective_students/_search.html.erb
  app/views/first_registration/prospective_students/edit.html.erb
  app/views/first_registration/prospective_students/index.html.erb
  app/views/first_registration/prospective_students/new.html.erb
  app/views/first_registration/prospective_students/show.html.erb
  app/views/units/_form.html.erb
  app/views/users/_addresses.html.erb
  app/views/users/_identities.html.erb
  config/locales/controllers/first_registration/prospective_students.en.yml
  config/locales/controllers/first_registration/prospective_students.tr.yml
  config/routes/first_registration.rb
  db/migrate/20190304052823_add_term_and_expiry_date_to_prospective_student.rb
  db/structure.sql
  lib/tasks/nokul/archive_prospective_students.rake
  lib/tasks/quality.rake
  plugins/tenant/common/lib/nokul/tenant/api.rb
  test/controllers/first_registration/prospective_students_controller_test.rb
  test/fixtures/prospective_students.yml
  test/models/academic_term_test.rb
  test/models/prospective_student_test.rb
Labels: feature step

#858 Add a rake task checking development machine prerequisities
  .rubocop.yml
  app/controllers/concerns/reference_resource.rb
  doc/development/installation.md
  lib/tasks/developer.rake
  lib/tasks/pull_request.rake
  plugins/tenant/omu/test/dummy/tmp/development_secret.txt
Labels: improvement

#859 Tenant credentials
  .github/CONTRIBUTING.md
  Dockerfile
  app/services/xokul/connection.rb
  config/credentials.yml.enc
  config/environments/production.rb
  config/initializers/rollbar.rb
  config/storage.yml
  doc/development/secrets.md
  docker-compose.yml
  lib/tasks/developer.rake
  plugins/support/doc/sensitive.md
  plugins/tenant/common/lib/nokul/tenant/api.rb
  plugins/tenant/omu/.gitignore
  plugins/tenant/omu/test/dummy/config/credentials.yml.enc
Labels: improvement

#866 Bump Ruby version to 2.6.2
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  plugins/support/.ruby-version
  plugins/support/Gemfile.lock
  plugins/tenant/common/.ruby-version
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/.ruby-version
  plugins/tenant/omu/Gemfile.lock
Labels: system

#865 Tidy up
  .env.sample
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app.json
  app/lib/nokul/database_url.rb
  app/lib/nokul/name.rb
  app/lib/nokul/version.rb
  app/views/layouts/shared/_footer.html.erb
  config/application.rb
  config/database.yml
  config/initializers/filter_parameter_logging.rb
  doc/postgresql/configuration.md
  lib/tasks/developer.rake
  lib/tasks/pull_request.rake
  lib/tasks/release.rake
  lib/tasks/security.rake
  test/config/application_config_test.rb
  test/config/database_config_test.rb
  test/helpers/link_helper_test.rb
  test/lib/application_name_test.rb
  test/lib/database_url_test.rb
  test/lib/version_test.rb
  yarn.lock
Labels: improvement

#863 Açılan derslerde en az bir grup oluşturulmasını zorunlu hale getir
  app/controllers/course_management/available_courses_controller.rb
  app/decorators/curriculum_decorator.rb
  app/models/available_course.rb
  app/views/course_management/available_courses/_form.html.erb
  app/views/course_management/available_courses/_group_fields.html.erb
  app/views/course_management/available_courses/_groups.html.erb
  app/views/course_management/available_courses/_js.html.erb
  app/views/course_management/available_courses/_lecturer_fields.html.erb
  app/views/course_management/available_courses/_search.html.erb
  app/views/course_management/available_courses/edit.html.erb
  app/views/course_management/available_courses/index.html.erb
  app/views/course_management/available_courses/new.html.erb
  app/views/course_management/available_courses/show.html.erb
  app/views/first_registration/prospective_students/show.html.erb
  config/locales/controllers/course_management/available_courses.en.yml
  config/locales/controllers/course_management/available_courses.tr.yml
  config/locales/controllers/first_registration/prospective_students.en.yml
  config/locales/controllers/first_registration/prospective_students.tr.yml
  test/controllers/course_management/available_courses_controller_test.rb
  test/models/available_course_test.rb
Labels: bug, improvement

#867 Remove beta environment
  .rubocop.yml
  Dockerfile
  app/jobs/application_job.rb
  config/cable.yml
  config/database.yml
  config/environments/beta.rb
  config/initializers/sidekiq.rb
  test/config/database_config_test.rb
Labels: improvement, system

#879 Add country specific sms regulations
  Gemfile.lock
  app/controllers/location/cities_controller.rb
  app/controllers/location/countries_controller.rb
  app/helpers/continent_helper.rb
  app/models/city.rb
  app/models/country.rb
  app/views/location/cities/_form.html.erb
  app/views/location/countries/_form.html.erb
  app/views/location/countries/show.html.erb
  config/locales/controllers/location/countries.en.yml
  config/locales/controllers/location/countries.tr.yml
  db/migrate/20190321163816_add_country_regulations_for_sms_to_countries.rb
  db/migrate/20190321213030_add_additional_fields_to_countries.rb
  db/migrate/20190321213059_add_additional_fields_to_cities.rb
  db/static_data/cities.yml
  db/static_data/countries.yml
  db/structure.sql
  lib/tasks/import/cities.rake
  lib/tasks/import/countries.rake
  plugins/support/Gemfile.lock
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/Gemfile.lock
  test/controllers/location/countries_controller_test.rb
  test/fixtures/cities.yml
  test/fixtures/countries.yml
  test/models/city_test.rb
  test/models/country_test.rb
  yarn.lock
Labels: feature step, improvement

#881 Nexmo and Twilio integration
  Gemfile
  Gemfile.lock
  app/errors/concatenation_error.rb
  app/errors/encoding_mismatch_error.rb
  app/errors/id_number_error.rb
  app/errors/invalid_phone_number_error.rb
  app/errors/unicode_support_error.rb
  app/services/nexmo/error_handler.rb
  app/services/nexmo/sms.rb
  app/services/twilio/lookup.rb
  app/services/twilio/sms.rb
  app/services/twilio/verify.rb
  app/views/location/countries/_form.html.erb
  config/application.rb
  config/initializers/authy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/nexmo.rb
  config/initializers/twilio.rb
  config/locales/errors/en.yml
  config/locales/errors/tr.yml
  plugins/tenant/omu/config/tenant.yml
  plugins/tenant/omu/test/dummy/config/credentials.yml.enc
  test/errors/id_number_error_test.rb
Labels: feature step

#883 Tidy up
  app/controllers/calendar_management/calendars_controller.rb
  app/services/academic_calendars/duplicate_calendar_service.rb
  app/services/duplicate_service.rb
  app/views/committee/agenda_types/index.html.erb
  app/views/course_management/available_courses/index.html.erb
  app/views/course_management/course_group_types/index.html.erb
  app/views/course_management/course_groups/index.html.erb
  app/views/course_management/course_types/index.html.erb
  app/views/course_management/courses/index.html.erb
  app/views/course_management/curriculums/index.html.erb
  app/views/first_registration/prospective_students/_search.html.erb
  app/views/first_registration/prospective_students/index.html.erb
  app/views/first_registration/prospective_students/show.html.erb
  app/views/first_registration/registration_documents/index.html.erb
  app/views/units/index.html.erb
  test/services/duplicate_calendar_service_test.rb
  test/services/duplicate_service_test.rb
Labels: bug

#884 Remove chromedriver-helper and selenium-webdriver, add webdrivers gem
  Gemfile
  Gemfile.lock
Labels: dependencies

#887 Fix markdownlint issues
  .markdownlintrc
  doc/README.md
  doc/development/app-upgrade.md
  doc/development/installation.md
  doc/development/rake-task.md
  doc/development/secrets.md
  doc/development/seed.md
  doc/development/test-coverage.md
  doc/development/test-data.md
  doc/development/test-unit.md
  doc/development/third-parties.md
  doc/development/virtualization.md
  doc/diagrams/README.md
  doc/git/authoring.md
  doc/git/branch.md
  doc/git/commit.md
  doc/git/issue.md
  doc/git/pull-request.md
  doc/git/review.md
  doc/helpers/javascripts/dynamic_select.md
  doc/helpers/link_to_helper.md
  doc/howto/navigate-units.md
  doc/howto/navigate-users.md
  doc/howto/tenant.md
  doc/ops/dokku.md
  doc/postgresql/configuration.md
  doc/postgresql/constraint-not-null-presence.md
  doc/postgresql/constraint-unique.md
  doc/postgresql/other-arel-queries.md
  doc/postgresql/type-boolean.md
  doc/postgresql/type-float-decimal.md
  doc/postgresql/type-integer.md
  doc/postgresql/type-reference.md
  doc/postgresql/type-string.md
  doc/postgresql/type-text.md
  doc/rule/validations.md
Labels: improvement
