Repository omu/nokul, pull requests merged in 2019-05, with the labels that each got.

#905 Upgrade pagy and other dependencies
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/initializers/pagy.rb
  config/locales/gems/pagy/en.yml
  config/locales/gems/pagy/tr.yml
Labels: dependencies

#904 Create prospective employee
  app/controllers/account/employees_controller.rb
  app/controllers/first_registration/prospective_employees_controller.rb
  app/controllers/first_registration/prospective_students_controller.rb
  app/models/concerns/prospective.rb
  app/models/employee.rb
  app/models/prospective_employee.rb
  app/models/prospective_student.rb
  app/services/first_registration/prospective_service.rb
  app/services/first_registration/prospective_student_service.rb
  app/views/account/employees/_form.html.erb
  app/views/first_registration/prospective_employees/_form.html.erb
  app/views/first_registration/prospective_employees/_search.html.erb
  app/views/first_registration/prospective_employees/edit.html.erb
  app/views/first_registration/prospective_employees/index.html.erb
  app/views/first_registration/prospective_employees/new.html.erb
  app/views/first_registration/prospective_students/_form.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  app/views/users/_employees.html.erb
  config/locales/controllers/first_registration/prospective_employees.en.yml
  config/locales/controllers/first_registration/prospective_employees.tr.yml
  config/locales/controllers/first_registration/prospective_students.en.yml
  config/locales/controllers/first_registration/prospective_students.tr.yml
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/routes/first_registration.rb
  db/migrate/20190419113152_create_prospective_employees.rb
  db/migrate/20190425065306_add_staff_number_to_employee.rb
  db/structure.sql
  test/controllers/accounts/employees_controller_test.rb
  test/controllers/first_registration/prospective_employees_controller_test.rb
  test/controllers/first_registration/prospective_students_controller_test.rb
  test/fixtures/employees.yml
  test/fixtures/prospective_employees.yml
  test/fixtures/prospective_students.yml
  test/models/concerns/prospective_test.rb
  test/models/employee_test.rb
  test/models/prospective_employee_test.rb
  test/models/prospective_student_test.rb
  test/services/first_registration/prospective_service_test.rb
  test/services/first_registration/prospective_student_service_test.rb
Labels: bug, feature step

#908 Aday personellerin hesap aktifleştirmesini sağla
  app/controllers/account/activations_controller.rb
  app/controllers/first_registration/prospective_employees_controller.rb
  app/services/activation/activation_service.rb
  app/services/first_registration/prospective_service.rb
  config/locales/layouts/shared/sidebar_tr.yml
  test/services/activation/activation_service_test.rb
Labels: feature step

#907 Add effective_unit_id and disable new registrations
  app/controllers/account/registrations_controller.rb
  app/controllers/application_controller.rb
  app/controllers/units_controller.rb
  app/views/account/addresses/_form.html.erb
  app/views/account/passwords/new.html.erb
  app/views/account/registrations/new.html.erb
  app/views/units/_form.html.erb
  config/locales/controllers/account/confirmations.tr.yml
  config/locales/controllers/account/passwords.en.yml
  config/locales/controllers/account/passwords.tr.yml
  config/locales/controllers/account/registrations.en.yml
  config/locales/controllers/account/registrations.tr.yml
  config/locales/controllers/account/sessions.en.yml
  config/locales/controllers/account/sessions.tr.yml
  config/locales/defaults/rails/tr.yml
  config/locales/models/units/en.yml
  config/locales/models/units/tr.yml
  config/routes/account.rb
  db/migrate/20190507195222_add_effective_yoksis_id_to_units.rb
  db/structure.sql
  lib/tasks/import/units.rake
  plugins/tenant/omu/config/tenant.yml
  test/system/reset_password_flow_test.rb
  test/system/sign_up_page_flow_test.rb
Labels: improvement
