Repository omu/nokul, pull requests merged in 2019-10, with the labels that each got.

#1036 MEKSIS servisini entegre et
  app/assets/images/meksis/baum.png
  app/assets/images/meksis/omu.jpg
  app/controllers/meksis/buildings_controller.rb
  app/controllers/meksis/classrooms_controller.rb
  app/controllers/meksis/dashboard_controller.rb
  app/controllers/meksis/place_types_controller.rb
  app/models/building.rb
  app/models/classroom.rb
  app/models/place_type.rb
  app/services/xokul/meksis.rb
  app/views/layouts/shared/_sidebar.html.erb
  app/views/meksis/buildings/_search.html.erb
  app/views/meksis/buildings/_select2.html.erb
  app/views/meksis/buildings/_stats.html.erb
  app/views/meksis/buildings/edit.html.erb
  app/views/meksis/buildings/index.html.erb
  app/views/meksis/buildings/index.pdf.erb
  app/views/meksis/buildings/show.html.erb
  app/views/meksis/classrooms/_search.html.erb
  app/views/meksis/classrooms/_select2.html.erb
  app/views/meksis/classrooms/index.html.erb
  app/views/meksis/classrooms/show.html.erb
  app/views/meksis/dashboard/_card.html.erb
  app/views/meksis/dashboard/index.html.erb
  app/views/meksis/place_types/index.html.erb
  app/views/meksis/place_types/show.html.erb
  config/locales/controllers/meksis/buildings.en.yml
  config/locales/controllers/meksis/buildings.tr.yml
  config/locales/controllers/meksis/classrooms.en.yml
  config/locales/controllers/meksis/classrooms.tr.yml
  config/locales/controllers/meksis/dashboard.en.yml
  config/locales/controllers/meksis/dashboard.tr.yml
  config/locales/controllers/meksis/place_types.en.yml
  config/locales/controllers/meksis/place_types.tr.yml
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/routes.rb
  config/routes/meksis.rb
  db/migrate/20191003075056_create_place_types.rb
  db/migrate/20191003100000_create_buildings.rb
  db/migrate/20191003102101_create_classrooms.rb
  db/structure.sql
  lib/tasks/fetch/buildings.rake
  lib/tasks/fetch/classrooms.rake
  lib/tasks/fetch/place_types.rake
  test/controllers/meksis/buildings_controller_test.rb
  test/controllers/meksis/classrooms_controller_test.rb
  test/controllers/meksis/dashboard_controller_test.rb
  test/controllers/meksis/place_types_controller_test.rb
  test/fixtures/buildings.yml
  test/fixtures/classrooms.yml
  test/fixtures/place_types.yml
  test/models/building_test.rb
  test/models/classroom_test.rb
  test/models/place_type_test.rb
Labels: feature

#1033 Profil sayfası oluştur
  app/controllers/account/profile_settings_controller.rb
  app/controllers/account/profiles_controller.rb
  app/controllers/account/settings/preferences/profiles_controller.rb
  app/helpers/apa_helper.rb
  app/jobs/yoksis/academic_credentials_save_job.rb
  app/jobs/yoksis/articles_save_job.rb
  app/jobs/yoksis/certifications_save_job.rb
  app/jobs/yoksis/education_informations_save_job.rb
  app/jobs/yoksis/projects_save_job.rb
  app/models/academic_credential.rb
  app/models/article.rb
  app/models/education_information.rb
  app/models/user.rb
  app/views/account/profiles/_academic_credentials.html.erb
  app/views/account/profiles/_articles.html.erb
  app/views/account/profiles/_certifications.html.erb
  app/views/account/profiles/_education_informations.html.erb
  app/views/account/profiles/_projects.html.erb
  app/views/account/profiles/edit.html.erb
  app/views/account/profiles/show.html.erb
  app/views/account/settings/index.html.erb
  app/views/account/settings/preferences/profiles/edit.html.erb
  app/views/layouts/shared/_header.html.erb
  config/locales/controllers/account/profile.en.yml
  config/locales/controllers/account/profile.tr.yml
  config/locales/controllers/account/profiles.en.yml
  config/locales/controllers/account/profiles.tr.yml
  config/locales/controllers/account/settings.en.yml
  config/locales/controllers/account/settings.tr.yml
  config/locales/controllers/account/settings/passwords.tr.yml
  config/locales/controllers/account/settings/preferences.en.yml
  config/locales/controllers/account/settings/preferences.tr.yml
  config/locales/models/certifications/en.yml
  config/locales/models/certifications/tr.yml
  config/locales/models/projects/en.yml
  config/locales/models/projects/tr.yml
  config/routes/account.rb
  db/migrate/20190925063737_create_academic_credentials.rb
  db/migrate/20190927071636_create_education_informations.rb
  db/structure.sql
  test/fixtures/academic_credentials.yml
  test/fixtures/education_informations.yml
  test/models/academic_credential_test.rb
  test/models/education_information_test.rb
  test/system/profile_setting_flow_test.rb
Labels: feature

#1067 Yazım hatasını düzelt
  .rubocop_common.yml
  app/validators/employee_validator.rb
  doc/README.md
  plugins/support/.rubocop.yml
  plugins/support/lib/nokul/support/minitest/association_helper.rb
  plugins/tenant/common/.rubocop.yml
  plugins/tenant/omu/.rubocop.yml
Labels: chore

#1072 Hata düzeltmeleri ve kod iyileştirmeleri yap
  Procfile
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/intl_tel_input.css
  app/assets/stylesheets/pdf.scss
  app/controllers/account/addresses_controller.rb
  app/controllers/account/identities_controller.rb
  app/decorators/user_decorator.rb
  app/jobs/ldap/entity_save_job.rb
  app/jobs/ldap/sync_job.rb
  app/models/concerns/ldap_sync_trigger.rb
  app/models/duty.rb
  app/models/employee.rb
  app/models/identity.rb
  app/models/ldap_entity.rb
  app/models/student.rb
  app/models/user.rb
  app/services/ldap/client.rb
  app/services/ldap/entity.rb
  app/services/ldap/sync.rb
  app/services/ldap/trigger.rb
  app/services/ldap/user_decorator.rb
  app/views/account/addresses/index.html.erb
  app/views/account/identities/index.html.erb
  app/views/account/settings/phones/edit.html.erb
  app/views/layouts/pdf.html.erb
  app/views/ldap_entities/_entity.html.erb
  app/views/users/_addresses.html.erb
  app/views/users/_identities.html.erb
  app/views/users/show.html.erb
  config/initializers/assets.rb
  config/initializers/zeitwerk.rb
  config/locales/models/identities/en.yml
  config/locales/models/identities/tr.yml
  config/locales/models/user/en.yml
  docker-compose.yml
  plugins/support/lib/nokul/support/rest_client.rb
  test/controllers/accounts/addresses_controller_test.rb
  test/controllers/accounts/identities_controller_test.rb
  test/controllers/patron/roles_controller_test.rb
  test/jobs/ldap_entity_save_job_test.rb
  test/jobs/ldap_sync_job_test.rb
  test/services/ldap/entity_test.rb
  test/services/ldap/user_decorator_test.rb
Labels: improvement

#1083 MEKSIS bina listesinden alınan PDF'teki asset yükleyememe sorununu düzelt
  app/views/meksis/buildings/index.pdf.erb
Labels: bug

#1080 REST ve Xokul istemcisini refaktör et
  app/services/xokul/connection.rb
  doc/app/xokul.md
  plugins/support/lib/nokul/support/rest_client.rb
Labels: improvement, urgent

#1098 Öğrenci aktif dönemde alabileceği dersleri görüntüleyebilsin
  app/controllers/course_management/available_courses_controller.rb
  app/controllers/course_management/enrolled_courses_controller.rb
  app/decorators/curriculum_decorator.rb
  app/decorators/curriculum_semester_decorator.rb
  app/decorators/prospective_student_decorator.rb
  app/decorators/student_decorator.rb
  app/models/available_course.rb
  app/models/calendar.rb
  app/models/course.rb
  app/models/curriculum_course.rb
  app/models/curriculum_semester.rb
  app/models/student.rb
  app/views/course_management/available_courses/_form.html.erb
  app/views/course_management/available_courses/_js.html.erb
  app/views/course_management/available_courses/index.html.erb
  app/views/course_management/available_courses/show.html.erb
  app/views/course_management/curriculum_courses/_form.html.erb
  app/views/course_management/enrolled_courses/_available_courses.html.erb
  app/views/course_management/enrolled_courses/_semesters.html.erb
  app/views/course_management/enrolled_courses/index.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/controllers/course_management/available_courses.en.yml
  config/locales/controllers/course_management/available_courses.tr.yml
  config/locales/controllers/course_management/enrolled_courses.en.yml
  config/locales/controllers/course_management/enrolled_courses.tr.yml
  config/locales/layouts/shared/sidebar_en.yml
  config/locales/layouts/shared/sidebar_tr.yml
  config/routes/course_management.rb
  db/migrate/20191007074407_fix_course_reference_to_curriculum_course_reference_on_available_courses.rb
  db/structure.sql
  test/controllers/course_management/available_courses_controller_test.rb
  test/controllers/course_management/curriculum_course_groups_controller_test.rb
  test/controllers/course_management/curriculum_courses_controller_test.rb
  test/controllers/course_management/enrolled_courses_controller_test.rb
  test/controllers/first_registration/prospective_students_controller_test.rb
  test/decorators/curriculum_decorator_test.rb
  test/decorators/curriculum_semester_decorator_test.rb
  test/decorators/prospective_student_decorator_test.rb
  test/decorators/student_decorator_test.rb
  test/fixtures/academic_terms.yml
  test/fixtures/available_courses.yml
  test/fixtures/calendar_events.yml
  test/fixtures/calendars.yml
  test/fixtures/curriculum_programs.yml
  test/fixtures/prospective_students.yml
  test/fixtures/students.yml
  test/fixtures/unit_calendars.yml
  test/fixtures/units.yml
  test/models/academic_term_test.rb
  test/models/available_course_test.rb
  test/models/calendar_test.rb
  test/models/course_test.rb
  test/models/curriculum_course_test.rb
  test/models/curriculum_semester_test.rb
  test/models/student_test.rb
Labels: feature

#1038 Yetkilendirme kapsam oluşturma yapısını iyileştir
  Gemfile
  Gemfile.lock
  app/assets/javascripts/shared/loading.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/loading.css
  app/controllers/application_controller.rb
  app/controllers/concerns/patron/searchable_module.rb
  app/controllers/patron/assignments_controller.rb
  app/controllers/patron/confirmations_controller.rb
  app/controllers/patron/query_stores_controller.rb
  app/controllers/patron/roles_controller.rb
  app/helpers/component_helper.rb
  app/lib/patron.rb
  app/lib/patron/scope/base.rb
  app/lib/patron/scope/dsl.rb
  app/lib/patron/scope/query/arel.rb
  app/lib/patron/scope/query/builder.rb
  app/lib/patron/scope/query/parameter.rb
  app/lib/patron/scope/store/accessor.rb
  app/lib/patron/scope/store/validation.rb
  app/lib/patron/scope/view/form.rb
  app/lib/patron/sudo.rb
  app/lib/patron/sudoable.rb
  app/lib/patron/utils/i18n.rb
  app/models/patron/query_store.rb
  app/scopes/unit_scope.rb
  app/views/course_management/curriculums/_curriculum_courses.html.erb
  app/views/course_management/curriculums/_semesters.html.erb
  app/views/patron/components/_preview.html.erb
  app/views/patron/components/_query_stores.html.erb
  app/views/patron/components/_smart_search_form.html.erb
  app/views/patron/confirmations/new.html.erb
  app/views/patron/query_stores/_filter.html.erb
  app/views/patron/query_stores/_form.html.erb
  app/views/patron/query_stores/preview.html.erb
  app/views/patron/query_stores/preview.js.erb
  app/views/patron/query_stores/show.html.erb
  config/initializers/assets.rb
  config/locales/controllers/patron/components.en.yml
  config/locales/controllers/patron/components.tr.yml
  config/locales/controllers/patron/confirmations.en.yml
  config/locales/controllers/patron/confirmations.tr.yml
  config/locales/controllers/patron/query_stores.en.yml
  config/locales/controllers/patron/query_stores.tr.yml
  config/locales/defaults/en.yml
  config/locales/defaults/tr.yml
  config/locales/patron/en.yml
  config/locales/patron/tr.yml
  config/routes/patron.rb
  doc/app/patron.md
  doc/app/sudo.md
  doc/helpers/component_helper.md
  test/controllers/patron/query_stores_controller_test.rb
  test/controllers/patron/roles_controller_test.rb
  test/fixtures/patron/query_stores.yml
  test/fixtures/patron/scope_assignments.yml
  test/lib/patron/scope/query/arel_test.rb
  test/lib/patron/sudo_test.rb
  test/models/patron/query_store_test.rb
  test/test_helper.rb
Labels: improvement

#1081 Personel profil sayfasında kitap bilgileri görüntülensin
  app/controllers/account/profiles_controller.rb
  app/helpers/apa_helper.rb
  app/jobs/yoksis/books_save_job.rb
  app/models/book.rb
  app/models/user.rb
  app/views/account/profiles/_articles.html.erb
  app/views/account/profiles/_books.html.erb
  app/views/account/profiles/show.html.erb
  app/views/studies/articles/index.html.erb
  config/locales/controllers/account/profiles.en.yml
  config/locales/controllers/account/profiles.tr.yml
  config/routes/account.rb
  db/migrate/20191008065752_create_books.rb
  db/structure.sql
  test/fixtures/books.yml
  test/models/book_test.rb
Labels: feature

#1110 Şifre yerine parola kullan
  config/locales/controllers/account/settings.tr.yml
Labels: chore

#1135 Yazım hatalarını düzelt
  config/locales/controllers/account/devise.tr.yml
  config/locales/controllers/account/passwords.tr.yml
  config/locales/controllers/account/unlocks.tr.yml
  config/locales/controllers/course_management/available_course_groups.tr.yml
  config/locales/controllers/course_management/available_courses.tr.yml
  config/locales/controllers/first_registration/prospective_employees.tr.yml
  config/locales/controllers/patron/assignments.tr.yml
  config/locales/models/account/tr.yml
  config/locales/models/user/tr.yml
Labels: chore

#1139 Improve mobile app mode with PWA.
  app/assets/images/logo/baum-logo-144.png
  app/assets/images/logo/baum-logo-192.png
  app/assets/images/logo/baum-logo-36.png
  app/assets/images/logo/baum-logo-48.png
  app/assets/images/logo/baum-logo-72.png
  app/assets/images/logo/baum-logo-96.png
  app/controllers/service_workers/manifests_controller.rb
  app/controllers/service_workers/workers_controller.rb
  app/javascript/packs/application.js
  app/views/layouts/shared/_meta.html.erb
  app/views/service_workers/manifests/index.json.erb
  app/views/service_workers/workers/index.js.erb
  config/environments/development.rb
  config/routes.rb
  db/encrypted_data/sample_data.sql.enc.gz
  public/site.webmanifest
Labels: feature

#1158 Lograge gem'ini ekle
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/initializers/lograge.rb
Labels: improvement
