Repository omu/nokul, pull requests merged in 2019-11, with the labels that each got.

#1160 Fix for PWA ios
  app/assets/images/logo/baum-logo-ipad-retina.png
  app/assets/images/logo/baum-logo-ipad.png
  app/assets/images/logo/baum-logo-iphone-retina.png
  app/views/layouts/shared/_meta.html.erb
  app/views/service_workers/manifests/index.json.erb
Labels: improvement

#1162 Git LFS'i iş akışından kaldır
  .gitignore
  db/encrypted_data/sample_data.sql.enc.gz
  db/encrypted_data/static_data.sql.enc.gz
  lib/scripts/deploy.sh
  lib/scripts/paas.sh
  lib/tasks/s3.rake
  lib/templates/ldap/openldap-2.4-bcyrpt-module.tar.gz
  plugins/tenant/omu/test/dummy/config/credentials.yml.enc
Labels: debt, improvement

#1178 Upgrade dependencies
  Gemfile.lock
  config/initializers/zeitwerk.rb
  plugins/support/Gemfile.lock
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/Gemfile.lock
Labels: dependencies

#1195 Fix staff number validation
  app/models/employee.rb
  test/fixtures/employees.yml
Labels: bug

#1197 Binalarda koordinatlar için uniqueness validasyonunu kaldır
  db/migrate/20191111082956_remove_unique_constraint_from_buildings.rb
  db/structure.sql
Labels: bug

#1203 Mekan türlerinin indeks sayfası için builder kullanma
  app/views/meksis/place_types/_search.html.erb
  app/views/meksis/place_types/index.html.erb
  config/locales/controllers/meksis/place_types.en.yml
  config/locales/controllers/meksis/place_types.tr.yml
Labels: bug

#1204 Fix seed
  db/beta_seed/curriculum.rb
Labels: bug

#1206 Update Codacy Badge
  README.md
Labels: chore

#1208 Tenant değişikliği sonrası ortaya çıkan hataları düzelt
  Dockerfile
  app/controllers/application_controller.rb
  test/config/tenant_config_test.rb
  test/services/ldap/entity_test.rb
Labels: improvement

#1214 OMU tenant'ının master key'ini değiştir
  .gitignore
  plugins/tenant/acme/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/test.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/test.yml.enc
Labels: improvement, security

#1216 Çeviri hatasını düzelt
  config/locales/defaults/tr.yml
Labels: chore

#1215 Personel görevlendirmelerinin görüntülenmesini sağla
  app/controllers/account/duties_controller.rb
  app/models/duty.rb
  app/validators/duty_validator.rb
  app/views/account/duties/_form.html.erb
  app/views/account/profiles/_academic_credentials.html.erb
  app/views/account/profiles/_duties.html.erb
  app/views/account/profiles/show.html.erb
  app/views/users/_employees.html.erb
  config/locales/controllers/account/profiles.en.yml
  config/locales/controllers/account/profiles.tr.yml
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  db/migrate/20191113054514_add_article_to_duty.rb
  db/structure.sql
Labels: feature

#1253 Sadece aktif personellik kullanılarak görevlendirme eklensin
  app/views/account/duties/_form.html.erb
Labels: qa

#1255 wkhtmltopdf-binary gemini kaldır
  Gemfile
  Gemfile.lock
Labels: bug

#1257 Profil sayfası arayüzünü değiştir
  app/assets/images/profile/female_avatar.svg
  app/assets/images/profile/male_avatar.svg
  app/controllers/account/profile_controller.rb
  app/controllers/account/profiles_controller.rb
  app/controllers/account/yoksis_services_controller.rb
  app/helpers/apa_helper.rb
  app/helpers/contact_link_helper.rb
  app/helpers/link_helper.rb
  app/views/account/profile/_academic_credentials.html.erb
  app/views/account/profile/_duties.html.erb
  app/views/account/profile/_education_informations.html.erb
  app/views/account/profile/articles.js.erb
  app/views/account/profile/books.js.erb
  app/views/account/profile/certifications.js.erb
  app/views/account/profile/edit.html.erb
  app/views/account/profile/index.html.erb
  app/views/account/profile/partials/_articles.html.erb
  app/views/account/profile/partials/_books.html.erb
  app/views/account/profile/partials/_certifications.html.erb
  app/views/account/profile/partials/_projects.html.erb
  app/views/account/profile/projects.js.erb
  app/views/account/profiles/_academic_credentials.html.erb
  app/views/account/profiles/_articles.html.erb
  app/views/account/profiles/_books.html.erb
  app/views/account/profiles/_certifications.html.erb
  app/views/account/profiles/_duties.html.erb
  app/views/account/profiles/_education_informations.html.erb
  app/views/account/profiles/_projects.html.erb
  app/views/account/profiles/show.html.erb
  config/locales/controllers/account/profile.en.yml
  config/locales/controllers/account/profile.tr.yml
  config/locales/controllers/account/profiles.en.yml
  config/locales/controllers/account/profiles.tr.yml
  config/locales/controllers/account/yoksis_services.en.yml
  config/locales/controllers/account/yoksis_services.tr.yml
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  config/routes/account.rb
  test/controllers/accounts/profile_settings_controller_test.rb
  test/system/profile_setting_flow_test.rb
Labels: improvement

#1260 Upgrade rubocop
  .erb-lint.yml
  .rubocop.yml
  .rubocop_common.yml
  Gemfile.lock
  app/lib/patron.rb
  config/application.rb
  db/seeds.rb
  lib/tasks/fetch/academic_staff.rake
  lib/tasks/fetch/references.rake
  lib/tasks/import/cities.rake
  lib/tasks/import/countries.rake
  lib/tasks/import/districts.rake
  lib/tasks/import/yoksis_countries.rake
  lib/tasks/prerequisities.rake
  lib/tasks/static_analysis/brakeman.rake
  lib/tasks/static_analysis/eslint.rake
  lib/tasks/static_analysis/executables.rake
  lib/tasks/static_analysis/html_linter.rake
  lib/tasks/static_analysis/liche.rake
  lib/tasks/static_analysis/markdownlint.rake
  lib/tasks/static_analysis/secrets.rake
  plugins/support/lib/nokul/support/sensitive.rb
  plugins/support/lib/nokul/support/utils/rake_utils.rb
  plugins/tenant/acme/test/dummy/Rakefile
  plugins/tenant/acme/test/dummy/config/environments/development.rb
  plugins/tenant/acme/test/dummy/test_tasks.rake
  plugins/tenant/common/.rubocop.yml
  plugins/tenant/common/lib/nokul/tenant/units/raw/det_many.rb
  plugins/tenant/common/lib/nokul/tenant/units/tasks/fetch.rake
  plugins/tenant/common/lib/nokul/tenant/units/tasks/issues.rake
  plugins/tenant/common/lib/nokul/tenant/units/tasks/reproduce.rake
  plugins/tenant/common/lib/nokul/tenant/units/tasks/stats.rake
  plugins/tenant/common/lib/nokul/tenant/units/tasks/tree.rake
  plugins/tenant/omu/test/dummy/Rakefile
  plugins/tenant/omu/test/dummy/config/environments/development.rb
  plugins/tenant/omu/test/dummy/test_tasks.rake
Labels: chore, improvement
