Repository omu/nokul, pull requests merged in 2020-08, with the labels that each got.

#1939 Telefon doğrulamasıyla parola sıfırlama işlemi yap
  Gemfile
  Gemfile.lock
  app/controllers/account/password_recovery_controller.rb
  app/services/password_recovery_service.rb
  app/views/account/password_recovery/edit.html.erb
  app/views/account/password_recovery/new.html.erb
  app/views/account/sessions/new.html.erb
  config/initializers/recaptcha.rb
  config/locales/controllers/account/password_recovery.en.yml
  config/locales/controllers/account/password_recovery.tr.yml
  config/locales/gems/recaptcha/tr.yml
  config/routes/account.rb
  plugins/tenant/acme/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/test.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/test.yml.enc
  test/controllers/account/password_recovery_controller_test.rb
  test/fixtures/users.yml
  test/services/password_recovery_service_test.rb
  test/system/reset_password_flow_test.rb
Labels: feature, improvement

#1960 Ortak rubocop yapılandırmalarını düzenle
  .rubocop.yml
Labels: chore

#1961 erb_lint gem'ini kaynağından kullan
  Gemfile
  Gemfile.lock
Labels: chore

#1981 Telefon doğrulama servisi ekle ve yerli sms sağlayıcıları kullan
  Gemfile
  Gemfile.lock
  app/controllers/account/password_recovery_controller.rb
  app/services/actions/prospective_student/registration.rb
  app/services/actions/user/verification.rb
  app/services/actions/user/verification/send.rb
  app/services/actions/user/verification/verify.rb
  app/services/password_recovery_service.rb
  config/initializers/redis.rb
  config/initializers/sms.rb
  config/locales/controllers/account/password_recovery.en.yml
  config/locales/controllers/account/password_recovery.tr.yml
  config/locales/verification/en.yml
  config/locales/verification/tr.yml
  doc/app/phone_verification.md
  plugins/tenant/acme/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/acme/test/dummy/config/credentials/test.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/development.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/production.yml.enc
  plugins/tenant/omu/test/dummy/config/credentials/test.yml.enc
  test/services/actions/prospective_student/registration_test.rb
  test/services/actions/user/verification/send_test.rb
  test/services/actions/user/verification/verify_test.rb
Labels: feature, improvement

#1997 Ruby sürümünü 2.7.1'e yükselt
  .ruby-version
  Dockerfile
  Gemfile.lock
  plugins/support/.ruby-version
  plugins/support/Gemfile.lock
  plugins/support/nokul-support.gemspec
  plugins/tenant/acme/.ruby-version
  plugins/tenant/acme/Gemfile.lock
  plugins/tenant/acme/nokul-tenant-acme.gemspec
  plugins/tenant/common/.ruby-version
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/common/nokul-tenant.gemspec
  plugins/tenant/omu/.ruby-version
  plugins/tenant/omu/Gemfile.lock
  plugins/tenant/omu/nokul-tenant-omu.gemspec
Labels: chore

#1998 Yarn upgrade
  yarn.lock
Labels: chore, dependencies

#2006 Plugin'lerdeki Ruby versiyon bağımlılığını kaldır
  .rubocop.yml
  plugins/support/nokul-support.gemspec
  plugins/tenant/acme/nokul-tenant-acme.gemspec
  plugins/tenant/common/nokul-tenant.gemspec
  plugins/tenant/omu/nokul-tenant-omu.gemspec
Labels: chore
