Repository omu/nokul, pull requests merged in 2020-02, with the labels that each got.

#1480 Tidy up
  app/controllers/course_management/curriculums_controller.rb
  app/models/curriculum.rb
  app/views/course_management/curriculums/_form.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  app/views/studentship/course_enrollments/_available_courses.html.erb
  config/environments/development.rb
  config/locales/controllers/course_management/curriculums.en.yml
  config/locales/controllers/course_management/curriculums.tr.yml
  config/routes.rb
  plugins/support/lib/nokul/support/minitest/validation_helper.rb
  test/controllers/course_management/curriculum_course_groups_controller_test.rb
  test/decorators/curriculum_semester_decorator_test.rb
  test/fixtures/curriculum_course_groups.yml
  test/fixtures/curriculum_courses.yml
  test/fixtures/curriculum_semesters.yml
  test/fixtures/curriculums.yml
  test/models/curriculum_test.rb
  test/services/student_course_enrollment_service_test.rb
Labels: improvement

#1481 Engel bilgisinin kişinin üzerinde tutulmasını sağla
  app/controllers/account/disability_controller.rb
  app/models/user.rb
  app/views/account/disability/edit.html.erb
  app/views/users/_disability.html.erb
  app/views/users/show.html.erb
  config/locales/controllers/account/disability.en.yml
  config/locales/controllers/account/disability.tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/routes/account.rb
  db/migrate/20200129072653_add_disability_to_user.rb
  db/structure.sql
  plugins/support/lib/nokul/support/codification/coder.rb
  test/models/user_test.rb
Labels: improvement

#1498 PDF üretimini basitçe test et
  test/system/wicked_pdf_test.rb
Labels: debt

#1496 Öğretim elemanı derslerini görüntüleyebilsin
  app/controllers/instructiveness/given_courses_controller.rb
  app/models/available_course.rb
  app/models/available_course_group.rb
  app/models/course_enrollment.rb
  app/models/employee.rb
  app/models/user.rb
  app/views/instructiveness/given_courses/_groups.html.erb
  app/views/instructiveness/given_courses/_search.html.erb
  app/views/instructiveness/given_courses/index.html.erb
  app/views/instructiveness/given_courses/show.html.erb
  app/views/instructiveness/given_courses/students.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/controllers/course_management/available_courses.en.yml
  config/locales/controllers/instructiveness/given_courses.en.yml
  config/locales/controllers/instructiveness/given_courses.tr.yml
  config/locales/layouts/shared/sidebar.en.yml
  config/locales/layouts/shared/sidebar.tr.yml
  config/routes.rb
  config/routes/instructiveness.rb
  test/controllers/instructiveness/given_courses_controller_test.rb
  test/fixtures/available_course_lecturers.yml
  test/fixtures/available_courses.yml
  test/models/available_course_group_test.rb
  test/models/available_course_test.rb
  test/models/course_enrollment_test.rb
  test/models/employee_test.rb
  test/models/user_test.rb
Labels: feature

#1499 Öğrencinin burslu olup olmadığının belirlenmesini sağla
  app/controllers/reference/scholarship_types_controller.rb
  app/controllers/students_controller.rb
  app/controllers/users_controller.rb
  app/models/scholarship_type.rb
  app/models/student.rb
  app/views/reference/dashboard/index.html.erb
  app/views/reference/scholarship_types/_form.html.erb
  app/views/reference/scholarship_types/edit.html.erb
  app/views/reference/scholarship_types/index.html.erb
  app/views/reference/scholarship_types/new.html.erb
  app/views/students/edit.html.erb
  app/views/users/_students.html.erb
  app/views/users/show.html.erb
  config/locales/controllers/reference/dashboard.en.yml
  config/locales/controllers/reference/dashboard.tr.yml
  config/locales/controllers/reference/scholarship_types.en.yml
  config/locales/controllers/reference/scholarship_types.tr.yml
  config/locales/controllers/students/en.yml
  config/locales/controllers/students/tr.yml
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  config/routes.rb
  config/routes/reference.rb
  db/migrate/20200206083358_create_scholarship_type.rb
  db/migrate/20200211084915_add_scholarship_type_to_student.rb
  db/structure.sql
  test/controllers/reference/scholarship_types_controller_test.rb
  test/controllers/students_controller.rb
  test/fixtures/scholarship_types.yml
  test/fixtures/students.yml
  test/models/scholarship_type_test.rb
  test/models/student_test.rb
Labels: feature

#1533 Öğretim elemanı not girişi yapabilmesini sağla
  app/controllers/instructiveness/assessments_controller.rb
  app/controllers/instructiveness/given_courses_controller.rb
  app/models/available_course.rb
  app/models/course_assessment_method.rb
  app/models/course_enrollment.rb
  app/models/course_evaluation_type.rb
  app/models/employee.rb
  app/models/grade.rb
  app/policies/instructiveness/assessment_policy.rb
  app/views/instructiveness/assessments/_assessment_info.html.erb
  app/views/instructiveness/assessments/edit.html.erb
  app/views/instructiveness/assessments/show.html.erb
  app/views/instructiveness/given_courses/_evaluation_types.html.erb
  app/views/instructiveness/given_courses/_groups.html.erb
  app/views/instructiveness/given_courses/show.html.erb
  app/views/instructiveness/given_courses/students.html.erb
  config/locales/controllers/instructiveness/assessments.en.yml
  config/locales/controllers/instructiveness/assessments.tr.yml
  config/locales/controllers/instructiveness/given_courses.en.yml
  config/locales/controllers/instructiveness/given_courses.tr.yml
  config/routes/instructiveness.rb
  db/migrate/20200213110520_create_grades.rb
  db/migrate/20200213124638_add_status_to_course_assessment_method.rb
  db/structure.sql
  test/controllers/instructiveness/assessments_controller_test.rb
  test/fixtures/available_course_lecturers.yml
  test/fixtures/available_courses.yml
  test/fixtures/course_assessment_methods.yml
  test/fixtures/course_enrollments.yml
  test/fixtures/course_evaluation_types.yml
  test/fixtures/grades.yml
  test/models/available_course_group_test.rb
  test/models/available_course_test.rb
  test/models/course_assessment_method_test.rb
  test/models/course_enrollment_test.rb
  test/models/employee_test.rb
  test/models/grade_test.rb
  test/policies/instructiveness/assessment_policy_test.rb
Labels: feature
