Repository omu/nokul, pull requests merged in 2020-05, with the labels that each got.

#1701 Not girişi işlemi için tarih aralığı kontrolü ekle
  app/controllers/instructiveness/assessments_controller.rb
  app/controllers/reference/evaluation_types_controller.rb
  app/controllers/studentship/course_enrollments_controller.rb
  app/decorators/assessment_decorator.rb
  app/decorators/calendar_event_decorator.rb
  app/decorators/student_decorator.rb
  app/models/available_course.rb
  app/models/course_assessment_method.rb
  app/models/course_enrollment.rb
  app/models/course_evaluation_type.rb
  app/models/evaluation_type.rb
  app/views/instructiveness/assessments/_assessment_info.html.erb
  app/views/instructiveness/assessments/show.html.erb
  app/views/instructiveness/given_courses/_evaluation_types.html.erb
  app/views/reference/evaluation_types/_form.html.erb
  app/views/reference/evaluation_types/index.html.erb
  app/views/studentship/course_enrollments/index.html.erb
  config/locales/controllers/calendar_management/calendar_events.en.yml
  config/locales/controllers/calendar_management/calendar_events.tr.yml
  config/locales/controllers/instructiveness/assessments.en.yml
  config/locales/controllers/instructiveness/assessments.tr.yml
  config/locales/controllers/instructiveness/given_courses.en.yml
  config/locales/controllers/instructiveness/given_courses.tr.yml
  config/locales/controllers/reference/evaluation_types.en.yml
  config/locales/controllers/reference/evaluation_types.tr.yml
  config/locales/controllers/studentship/course_enrollments.en.yml
  config/locales/controllers/studentship/course_enrollments.tr.yml
  db/beta_seed/calendar.rb
  db/migrate/20200430130429_add_identifier_to_evaluation_type.rb
  db/structure.sql
  lib/tasks/fix_data.rake
  plugins/tenant/acme/db/static/event_types.yml
  plugins/tenant/omu/db/static/event_types.yml
  test/controllers/calendar_management/calendar_event_types_controller_test.rb
  test/controllers/reference/evaluation_types_controller_test.rb
  test/decorators/assessment_decorator_test.rb
  test/decorators/calendar_event_decorator_test.rb
  test/decorators/student_decorator_test.rb
  test/fixtures/calendar_event_types.yml
  test/fixtures/calendar_events.yml
  test/fixtures/evaluation_types.yml
  test/fixtures/unit_calendars.yml
  test/models/available_course_test.rb
  test/models/calendar_event_test.rb
  test/models/course_assessment_method_test.rb
  test/models/evaluation_type_test.rb
Labels: improvement

#1702 Harç borcu oluşturma sürecine hazırlık koşulunu ekle
  app/controllers/students_controller.rb
  app/controllers/user_management/users_controller.rb
  app/models/prospective_student.rb
  app/models/student.rb
  app/services/debt/tuition/process/daytime_education.rb
  app/views/reference/evaluation_types/index.html.erb
  app/views/students/edit.html.erb
  app/views/user_management/users/_students.html.erb
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  db/migrate/20200427103727_add_columns_to_student.rb
  db/structure.sql
  test/controllers/students_controller_test.rb
  test/fixtures/students.yml
  test/models/student_test.rb
Labels: debt, improvement

#1735 Upgrade bundler dependencies
  Gemfile.lock
  app/views/reference/document_types/_form.html.erb
Labels: dependencies

#1737 Ders açarken aktif görevlendirmesi olanların listelenmesini sağla
  app/models/unit.rb
  test/models/unit_test.rb
Labels: qa

#1740 Fix logout path
  app/views/layouts/shared/_header.html.erb
Labels: qa

#1741 Upgrade rack-oauth2
  Gemfile
  Gemfile.lock
Labels: improvement

#1760 Upgrade plugins dependencies
  Gemfile.lock
  plugins/support/Gemfile
  plugins/support/Gemfile.lock
  plugins/support/nokul-support.gemspec
  plugins/tenant/common/Gemfile
  plugins/tenant/common/Gemfile.lock
Labels: dependencies
