Repository omu/nokul, pull requests merged in 2020-07, with the labels that each got.

#1853 Codacy coverage entegrasyonunu düzelt
  .travis.yml
  Gemfile
  Gemfile.lock
  docker-compose.yml
  test/test_helper.rb
Labels: improvement

#1855 Xokul adaylar servisini entegre et
  app/services/xokul/yoksis/prospectives.rb
  doc/app/xokul.md
Labels: feature

#1864 YÖKSİS dönem türleri referansını ekle
  app/services/xokul/yoksis/references.rb
  doc/app/xokul.md
Labels: feature

#1867 PostgreSQL sürümünü 12.1'e yükselt
  docker-compose.yml
Labels: improvement

#1883 Açılan derslerde gruba aynı öğretim elemanının atanmasını engelle
  app/controllers/units_controller.rb
  app/validators/available_course_lecturer_validator.rb
  config/locales/validators/en.yml
  config/locales/validators/tr.yml
Labels: bug, qa

#1885 Yeni açılan derslerde eklenen grubun kaldırılabilmesini sağla
  app/views/course_management/available_courses/_group_fields.html.erb
Labels: bug, qa

#1887 Rubocop ve erblint hatalarını düzelt
  app/models/prospective_student.rb
  app/services/xokul/yoksis/references.rb
  app/views/first_registration/prospective_students/_fetch.html.erb
  app/views/user_management/users/_account.html.erb
  db/seeds.rb
Labels: bug

#1905 Aday öğrenci arama formundaki çeviri hatalarını düzelt.
  app/views/first_registration/prospective_students/_search.html.erb
  config/locales/controllers/first_registration/prospective_students.en.yml
  config/locales/controllers/first_registration/prospective_students.tr.yml
Labels: qa

#1906 Rails Edge sürümüne geçiş yap
  Gemfile
  Gemfile.lock
  app/validators/academic_term_validator.rb
  app/validators/address_and_identity_validator.rb
  app/validators/available_course_lecturer_validator.rb
  app/validators/course_evaluation_type_validator.rb
  app/validators/duty_validator.rb
  app/validators/employee_validator.rb
  app/validators/position_validator.rb
  app/validators/prospective_student_validator.rb
  app/views/meksis/buildings/_stats.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/test.rb
  db/migrate/20200713182117_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20200713182118_create_active_storage_variant_records.active_storage.rb
  db/seeds.rb
  db/structure.sql
  plugins/support/Gemfile
  plugins/support/lib/nokul/support/sensitive.rb
  plugins/tenant/acme/nokul-tenant-acme.gemspec
  plugins/tenant/common/Gemfile
  plugins/tenant/omu/nokul-tenant-omu.gemspec
  test/config/database_config_test.rb
  test/controllers/accounts/profile_settings_controller_test.rb
Labels: improvement

#1903 Yurt dışından kabul edilecek öğrenciler için harç borcu oluştur
  app/controllers/yoksis/student_entrance_types_controller.rb
  app/models/student.rb
  app/models/student_entrance_type.rb
  app/services/debt/tuition/debt.rb
  app/services/debt/tuition/dispatch.rb
  app/services/debt/tuition/process/abroad.rb
  app/services/debt/tuition/process/base.rb
  app/services/debt/tuition/process/daytime.rb
  app/services/debt/tuition/process/daytime_education.rb
  app/services/debt/tuition/process/evening.rb
  app/views/yoksis/student_entrance_types/_form.html.erb
  app/views/yoksis/student_entrance_types/index.html.erb
  config/locales/controllers/yoksis/student_entrance_types.en.yml
  config/locales/controllers/yoksis/student_entrance_types.tr.yml
  db/migrate/20200708072837_add_abroad_to_student_entrance_type.rb
  db/structure.sql
  test/fixtures/student_entrance_types.yml
  test/fixtures/students.yml
  test/fixtures/unit_tuitions.yml
  test/models/student_entrance_type_test.rb
  test/models/student_test.rb
  test/services/debt/tuition_debt_service_test.rb
Labels: feature
