Repository omu/nokul, pull requests merged in 2020-01, with the labels that each got.

#1376 Handle unverified request with reset_session
  app/controllers/application_controller.rb
  config/locales/errors/en.yml
  config/locales/errors/tr.yml
Labels: bug

#1394 Bump Ruby version to 2.7.0
  .ruby-version
  Dockerfile
  Gemfile.lock
  app.json
  app/decorators/student_decorator.rb
  app/lib/patron/scope/dsl.rb
  app/services/student_course_enrollment_service.rb
  plugins/support/.ruby-version
  plugins/support/Gemfile.lock
  plugins/support/lib/nokul/support/codification/coder.rb
  plugins/tenant/acme/.ruby-version
  plugins/tenant/acme/Gemfile.lock
  plugins/tenant/common/.ruby-version
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/.ruby-version
  plugins/tenant/omu/Gemfile.lock
  test/pundit_test_case.rb
  test/services/student_course_enrollment_service_test.rb
Labels: dependencies

#1393 Ders kayıt olma durumunun doğru yönetilmesini sağlayacak model ekle
  app/controllers/studentship/course_enrollments_controller.rb
  app/models/academic_term.rb
  app/models/course_enrollment.rb
  app/models/semester_registration.rb
  app/models/student.rb
  app/services/student_course_enrollment_service.rb
  app/views/studentship/course_enrollments/_student_info.html.erb
  app/views/studentship/course_enrollments/index.html.erb
  config/locales/controllers/studentship/course_enrollments.en.yml
  config/locales/controllers/studentship/course_enrollments.tr.yml
  db/migrate/20191226074849_create_semester_registrations.rb
  db/migrate/20200102083531_remove_semester_and_student_reference_from_course_enrollments.rb
  db/migrate/20200102083736_add_semester_registration_reference_to_course_enrollments.rb
  db/structure.sql
  test/controllers/studentship/course_enrollments_controller_test.rb
  test/fixtures/course_enrollments.yml
  test/fixtures/semester_registrations.yml
  test/models/academic_term_test.rb
  test/models/course_enrollment_test.rb
  test/models/semester_registration_test.rb
  test/models/student_test.rb
  test/services/student_course_enrollment_service_test.rb
Labels: improvement

#1395 Yetkilendirme modülünü iyileştir
  Gemfile
  Gemfile.lock
  app/controllers/patron/roles_controller.rb
  app/lib/patron/permission_builder.rb
  app/lib/patron/role_builder.rb
  app/lib/patron/roleable.rb
  app/lib/patron/scope/dsl.rb
  app/models/patron/permission.rb
  app/models/patron/role.rb
  app/models/patron/role_permission.rb
  app/policies/patron/assignment_policy.rb
  app/policies/patron/permission_policy.rb
  app/policies/patron/query_store_policy.rb
  app/policies/patron/role_policy.rb
  app/views/patron/components/_role_permissions.html.erb
  app/views/patron/roles/_form.html.erb
  app/views/patron/roles/_role_permission_fields.html.erb
  app/views/patron/roles/show.html.erb
  config/initializers/role_management.rb
  config/locales/controllers/patron/permissions.en.yml
  config/locales/controllers/patron/permissions.tr.yml
  config/locales/controllers/patron/role_permissions.en.yml
  config/locales/controllers/patron/role_permissions.tr.yml
  config/locales/controllers/patron/roles.en.yml
  config/locales/controllers/patron/roles.tr.yml
  config/locales/patron/en.yml
  config/locales/patron/tr.yml
  db/migrate/20191112123931_add_privileges_to_role_permission.rb
  db/structure.sql
  doc/app/patron.md
  lib/tasks/patron.rake
  test/controllers/patron/roles_controller_test.rb
  test/fixtures/patron/role_permissions.yml
Labels: feature

#1428 Oturumlar için timeout değerini düzenle
  app/controllers/account/sessions_controller.rb
  app/lib/nokul/sso.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/initializers/zeitwerk.rb
Labels: improvement

#1432 SDP kodlarını DETSİS tanımlarına ekle
  README.md
  app/controllers/detsis/dashboard_controller.rb
  app/controllers/detsis/sdp_codes_controller.rb
  app/models/sdp_code.rb
  app/services/xokul/detsis.rb
  app/views/detsis/dashboard/_card.html.erb
  app/views/detsis/dashboard/index.html.erb
  app/views/detsis/sdp_codes/_search.html.erb
  app/views/detsis/sdp_codes/index.html.erb
  app/views/layouts/shared/_sidebar.html.erb
  config/locales/controllers/detsis/dashboard.en.yml
  config/locales/controllers/detsis/dashboard.tr.yml
  config/locales/controllers/detsis/sdp_codes.en.yml
  config/locales/controllers/detsis/sdp_codes.tr.yml
  config/locales/layouts/mailer/en.yml
  config/locales/layouts/shared/meta.en.yml
  config/locales/layouts/shared/sidebar.en.yml
  config/locales/layouts/shared/sidebar.tr.yml
  config/routes.rb
  config/routes/detsis.rb
  db/migrate/20200122124332_create_sdp_codes.rb
  db/structure.sql
  lib/tasks/fetch/sdp_code_references.rake
  test/controllers/detsis/dashboard_controller_test.rb
  test/controllers/detsis/sdp_codes_controller_test.rb
  test/fixtures/sdp_codes.yml
  test/models/sdp_code_test.rb
Labels: feature

#1435 Fix typo
  config/locales/controllers/manager/stats/students.tr.yml
Labels: chore

#1437 Öğrencinin açılan ders grubunu seçmesini sağla
  app/controllers/studentship/course_enrollments_controller.rb
  app/models/available_course.rb
  app/models/available_course_group.rb
  app/models/course_enrollment.rb
  app/models/semester_registration.rb
  app/services/student_course_enrollment_service.rb
  app/views/studentship/course_enrollments/_available_courses.html.erb
  app/views/studentship/course_enrollments/_course_enrollments.html.erb
  app/views/studentship/course_enrollments/list.html.erb
  app/views/studentship/course_enrollments/new.html.erb
  config/locales/controllers/studentship/course_enrollments.en.yml
  config/locales/controllers/studentship/course_enrollments.tr.yml
  db/migrate/20200123164837_available_course_group_reference_to_course_enrollments.rb
  db/structure.sql
  test/controllers/studentship/course_enrollments_controller_test.rb
  test/fixtures/available_course_groups.yml
  test/fixtures/available_course_lecturers.yml
  test/fixtures/course_enrollments.yml
  test/fixtures/semester_registrations.yml
  test/models/available_course_group_test.rb
  test/models/available_course_test.rb
  test/models/course_enrollment_test.rb
  test/services/student_course_enrollment_service_test.rb
Labels: feature

#1462 Bina istatistiklerindeki sıralama yanlışını düzelt
  app/views/meksis/buildings/index.html.erb
Labels: bug

#1461 Sidekiq-cron gem'ini ekle
  Gemfile
  Gemfile.lock
  app/jobs/rake_job.rb
  config/initializers/sidekiq.rb
  config/schedule.yml
  doc/app/cron.md
Labels: feature

#1463 Schedule.yml dosyasını kaldır
  config/schedule.yml
Labels: bug
