Repository omu/nokul, pull requests merged in 2020-06, with the labels that each got.

#1758 Ders açma/silme işlemleri için tarih aralığı kontrolü ekle
  app/controllers/course_management/available_course_groups_controller.rb
  app/controllers/course_management/available_courses_controller.rb
  app/controllers/course_management/course_evaluation_types_controller.rb
  app/models/available_course.rb
  app/models/available_course_group.rb
  app/models/unit.rb
  app/views/course_management/available_courses/_evaluation_types.html.erb
  app/views/course_management/available_courses/_form.html.erb
  app/views/course_management/available_courses/_group_fields.html.erb
  app/views/course_management/available_courses/_groups.html.erb
  app/views/course_management/available_courses/index.html.erb
  app/views/course_management/available_courses/show.html.erb
  config/locales/controllers/course_management/available_course_groups.en.yml
  config/locales/controllers/course_management/available_course_groups.tr.yml
  config/locales/controllers/course_management/available_courses.en.yml
  config/locales/controllers/course_management/available_courses.tr.yml
  config/locales/controllers/course_management/course_evaluation_types.en.yml
  config/locales/controllers/course_management/course_evaluation_types.tr.yml
  lib/tasks/fix_data.rake
  plugins/tenant/acme/db/static/event_types.yml
  plugins/tenant/omu/db/static/event_types.yml
  test/controllers/course_management/available_course_groups_controller_test.rb
  test/controllers/course_management/available_courses_controller_test.rb
  test/controllers/course_management/course_evaluation_types_controller_test.rb
  test/fixtures/available_course_groups.yml
  test/fixtures/available_course_lecturers.yml
  test/fixtures/available_courses.yml
  test/fixtures/calendar_event_types.yml
  test/fixtures/calendar_events.yml
  test/fixtures/course_assessment_methods.yml
  test/fixtures/course_evaluation_types.yml
  test/models/available_course_group_test.rb
  test/models/available_course_test.rb
Labels: improvement

#1778 Öğrenci tarafında harç borcunun görüntülenmesini sağla
  app/controllers/studentship/tuition_debts_controller.rb
  app/policies/studentship/tuition_debt_policy.rb
  app/views/layouts/shared/menus/_student.html.erb
  app/views/studentship/tuition_debts/index.html.erb
  config/locales/controllers/studentship/tuition_debts.en.yml
  config/locales/controllers/studentship/tuition_debts.tr.yml
  config/locales/layouts/shared/sidebar.en.yml
  config/locales/layouts/shared/sidebar.tr.yml
  config/routes/studentship.rb
  test/controllers/studentship/tuition_debts_controller_test.rb
  test/policies/studentship/tuition_debt_policy_test.rb
Labels: feature

#1818 Yöksis özgeçmiş servisine göre ilgili verileri güncelle
  app/models/academic_credential.rb
  app/models/article.rb
  app/models/book.rb
  app/models/certification.rb
  app/models/education_information.rb
  app/models/paper.rb
  app/views/account/profile/index.html.erb
  app/views/account/profile/partials/_certifications.html.erb
  config/locales/models/account/en.yml
  config/locales/models/account/tr.yml
  config/locales/models/articles/en.yml
  config/locales/models/articles/tr.yml
  config/locales/models/books/en.yml
  config/locales/models/books/tr.yml
  config/locales/models/certifications/en.yml
  config/locales/models/certifications/tr.yml
  config/locales/models/papers/en.yml
  config/locales/models/papers/tr.yml
  config/locales/models/projects/en.yml
  config/locales/models/projects/tr.yml
  test/fixtures/academic_credentials.yml
  test/fixtures/education_informations.yml
  test/models/academic_credential_test.rb
  test/models/article_test.rb
  test/models/book_test.rb
  test/models/certification_test.rb
  test/models/education_information_test.rb
  test/models/paper_test.rb
Labels: qa

#1835 Ortak RuboCop yapılandırmasını uzak kaynaktan miras al
  .gitignore
  .rubocop.yml
  .rubocop_common.yml
Labels: improvement
