Repository omu/nokul, pull requests merged in 2020-03, with the labels that each got.

#1554 Birim harç ücretlerinin girilmesini sağla
  app/controllers/tuition_management/tuitions_controller.rb
  app/models/academic_term.rb
  app/models/tuition.rb
  app/models/unit.rb
  app/models/unit_tuition.rb
  app/policies/tuition_management/tuition_policy.rb
  app/validators/unit_tuition_validator.rb
  app/views/layouts/shared/menus/_admin.html.erb
  app/views/tuition_management/tuitions/_form.html.erb
  app/views/tuition_management/tuitions/_search.html.erb
  app/views/tuition_management/tuitions/_select2.html.erb
  app/views/tuition_management/tuitions/edit.html.erb
  app/views/tuition_management/tuitions/index.html.erb
  app/views/tuition_management/tuitions/new.html.erb
  app/views/tuition_management/tuitions/units.json.jbuilder
  config/initializers/role_management.rb
  config/locales/controllers/tuition_management/tuitions.en.yml
  config/locales/controllers/tuition_management/tuitions.tr.yml
  config/locales/layouts/shared/sidebar.en.yml
  config/locales/layouts/shared/sidebar.tr.yml
  config/locales/validators/en.yml
  config/locales/validators/tr.yml
  config/routes.rb
  config/routes/tuition_management.rb
  db/migrate/20200215132359_create_tuitions.rb
  db/migrate/20200217110305_create_unit_tuition.rb
  db/structure.sql
  test/controllers/tuition_management/tuitions_controller_test.rb
  test/fixtures/patron/permissions.yml
  test/fixtures/patron/role_permissions.yml
  test/fixtures/tuitions.yml
  test/fixtures/unit_tuitions.yml
  test/models/academic_term_test.rb
  test/models/tuition_test.rb
  test/models/unit_test.rb
  test/models/unit_tuition_test.rb
  test/policies/tuition_management/tuition_policy_test.rb
Labels: feature

#1571 Okulu uzatan öğrencilerin belirlenebilmesini sağla
  app/controllers/students_controller.rb
  app/models/prospective_student.rb
  app/models/student.rb
  app/views/students/edit.html.erb
  app/views/user_management/users/_students.html.erb
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  db/migrate/20200310101357_add_statusand_exceeded_education_period_to_student.rb
  db/structure.sql
  test/fixtures/students.yml
  test/models/student_test.rb
Labels: improvement

#1588 Öğrencinin hangi aşamada olduğunun belirlenmesini sağla
  app/controllers/students_controller.rb
  app/models/student.rb
  app/models/student_grade.rb
  app/views/students/edit.html.erb
  app/views/user_management/users/_students.html.erb
  config/locales/models/user/en.yml
  config/locales/models/user/tr.yml
  db/migrate/20200317094504_add_stage_to_student.rb
  db/structure.sql
  test/fixtures/student_grades.yml
  test/fixtures/students.yml
  test/models/student_grade_test.rb
  test/models/student_test.rb
Labels: feature

#1597 Upgrade dependencies
  Gemfile.lock
  plugins/support/Gemfile.lock
  plugins/tenant/acme/Gemfile.lock
  plugins/tenant/common/Gemfile.lock
  plugins/tenant/omu/Gemfile.lock
Labels: dependencies
